### ISSUE TITLE
Some questions about option of props 

### ISSUE THREAD

**Issue by Klay-Clam** [riophae/vue-treeselect#10]
Greetings,

The value of my options is initially null, but inside this component I'll change this value through the server. How do I assign values to my options after changing? I found that I can not now show the data to options after the data has been modified.

Thanks so much

**Comment by MuMuWang** [comment]
问题解决了么，我也遇到这个问题了

**Comment by Klay-Clam** [comment]
Sorry,not yet.I'm going to use other components.

**Comment by riophae** [comment]
@Klay-Clam Hey, did you mean change the selected options or change the `value` of an item in `options`?

**Comment by riophae** [comment]
指的是需要异步修改选中的项对吗？可以这样：

```html
<template>
  <treeselect v-model="value" options="options" />
</template>
```

```js
export {
  data: {
    value: null,
  },
  mounted() {
    // 在这里发送 AJAX 请求，然后修改 this.value 即可
  },
}
```
