### ISSUE TITLE
children的问题

### ISSUE THREAD

**Issue by fujianxiamen** [riophae/vue-treeselect#104]
如果当前节点没有子节点 children一点要为null，可以为空数组[]吗？现在的情况后端返回数据，如果没有子节点返回的children:[],这样的情况，现在需要在前端继续遍历一遍进行对children:null?

**Comment by riophae** [comment]
可以是空数组的，设置为 `null` 表示这个节点的子节点需要懒加载，设置为 `[]` 则不需要懒加载。

**Comment by fujianxiamen** [comment]
![qq 20180704180741](https://user-images.githubusercontent.com/20263914/42271336-a0e62840-7fb5-11e8-93e3-06cf24b3fc49.png)

[空数组是可以，但是有一问题，就是叶子节点前面还是出现三角形小图标，看上去像是还有子节点一样，我希望是如果叶子节点，不就要显示那个三角图标了，

**Comment by riophae** [comment]
如果是叶子节点的话，应该完全不要有 `children` 属性，或者让它为 `undefined` 也可以。空数组实际上仍然表示一个枝干节点。

**Comment by riophae** [comment]
我突然意识到问题所在了，是文档交代不够清楚吧。因为一般来说没有子节点的就是叶子节点，但是 vue-treeselect 里面，没有子节点也仍然可以是枝干节点。我需要调整一下文档。

**Comment by fujianxiamen** [comment]
作者你好，我还有一个问题，就是我为了增加节点小图标，采用slot自定义的节点，现在可以通过提供isBranch来判断是Branch还是leaf 从而也可以设置不同的小图标，但是我现在想Branch的节点打开与收起，再进一步显示不同的小图标，我需要通过什么值来判断节点打开与收起。谢谢

**Comment by riophae** [comment]
判断枝干/叶子用 `node.isBranch` 和 `node.isLeaf`，判断展开状态则是 `node.isExpanded`。此外还有一个 `node.isExpandedOnSearch`，表示同步搜索的时候该节点的展开状态。之所以分为两个，是因为这样可以实现更好的用户体验。

**Comment by fhefh2015** [comment]
去除children数组为空的方法
```javascript

let isObject = (arg) => typeof arg === 'object';

/**
 * 
 * @param {Object} o :: the object being cleaned
 * @param {String|Number} key :: the key or index to be cleaned from `o`
 */
function removeKey(o, key="") {

    if (key === "") {
        return o;
    }

    isObject(o) && Object.keys(o).forEach(function (k) {
        (k === key && o[k] && o[k].length === 0) && delete o[k] ||
            (o[k] && isObject(o[k]) && removeKey(o[k], key))
    });
    return o;
}

//使用方法
let data = removeKey(tree数组, 要去除的key名称)
```

**Comment by geXingW** [comment]
这位老哥提供的思路不错，无需遍历！！！

https://github.com/riophae/vue-treeselect/issues/158#issuecomment-700785680
