### ISSUE TITLE
搜索问题

### ISSUE THREAD

**Issue by markh5** [riophae/vue-treeselect#105]
你好，请问搜索只能基于label吗？
传入的options还有其他属性，能否支持搜索其他node.raw属性？

**Comment by riophae** [comment]
暂时不能，之后会添加的这方面支持的

**Comment by markh5** [comment]
我目前是这么处理的，把需要搜索的数据全部拼装到label上，并使用slot="option-label"显示想要显示的值。
但是有一个问题，就是当我是单选时，我选择了一项后，class名为vue-treeselect__single-value的div下会显示所有的label数据，请问让我点击完成后，如何不显示全部的label数据？

**Comment by riophae** [comment]
嗯……暂时那个 value 不支持自定义 label 显示。说到底还是应该改搜索的机制……

**Comment by markh5** [comment]
你好，看到您加入了matchKeys的特性，我简单看了下代码，用法是不是如下：

:match-keys="["label", "xx" ]" 
//xx为node.raw的属性？

**Comment by riophae** [comment]
是的，不过暂时还没发布

这个 `node.raw` 就是你传给 vue-treeselect 的节点对象（即便你用了 `normalizer` 参数，也仍然是这个 `node.raw`），而这个 `node` 则是 vue-treeselect 内部 normalize 过的节点对象（可能概念比较乱，之后我再调整下命名）。

**Comment by KouYidong** [comment]
问一下，那么自定义键名称那一块能具体说一下吗？小白一枚

**Comment by davisky** [comment]
<treeselect
            v-model="form.presenterId"
            :maxHeight="500"
            :options="options"
            placeholder="部门/班级/姓名/工号或学号"
            valueConsistsOf="LEAF_PRIORITY"
            :normalizer="normalizer"
            :disable-branch-nodes="true"
            search-nested
            :default-expand-level="1"
            :clearOnSelect="true"
            :append-to-body="true"
            defaultExpandLevel="0"
          />

目前使用的这个配置，没有使用异步来搜索数据，数据到10000条左右，会有明显的卡顿，大佬们有没有给我合理的建议呀
