### ISSUE TITLE
展开列表，会回到顶部

### ISSUE THREAD

**Issue by markh5** [riophae/vue-treeselect#106]
![image](https://user-images.githubusercontent.com/16110230/41147380-d84bad1e-6b38-11e8-8d52-8ad8dfaa53e9.png)
![image](https://user-images.githubusercontent.com/16110230/41147422-f18d4a44-6b38-11e8-90d6-5de3982ae48f.png)
你好，当滚动到浏览器窗口外的位置时，点击展开，浏览器会回到顶部后，列表再展开，这是为什么？

**Comment by markh5** [comment]
刚刚描述的可能不太清除，当我的tree是alwaysOpen的状态下，我点击一个节点，节点展开的瞬间，input会瞬间focus，导致浏览器回滚到顶部

**Comment by riophae** [comment]
你好，先更新到 v0.0.29 试试看？

**Comment by riophae** [comment]
猜测跟这个有关系：https://github.com/riophae/vue-treeselect/commit/9f4c0df1b18e2d29afb1a3ede629ae71a4a795b2

**Comment by markh5** [comment]
你好，更新到v0.0.29还是存在focus的问题

![image](https://user-images.githubusercontent.com/16110230/41580999-a79e8f2a-73cf-11e8-883d-5d48e787ecd9.png)

**Comment by riophae** [comment]
我刚才又试了下，还是没能重现。可以用这个 [pen](https://codepen.io/riophae/pen/MExgzP) 做一个 bug 演示的 demo 吗？

**Comment by markh5** [comment]
找了半天发现是我的问题，我将css设置为
.vue-treeselect__menu{
    max-height: 100vh !important;
 }

导致滚动时搜索框也随之滚动，然后展开的瞬间focus，滚到页面顶部了。

**Comment by markh5** [comment]
![image](https://user-images.githubusercontent.com/16110230/41636112-228c1612-747f-11e8-8e88-36309e2cbb27.png)
vue-treeselect部分设置flex:1; overflow-y: auto;
为了符合整体的UI格式，我强行覆盖了部分样式。
![Uploading image.png…]()

现在问题是我如何让vue-treeselect的高度通过内容撑开，并且搜索框随着滚动依旧固定在最上面。
（我将.vue-treeselect__menu的max-height强行设置为none后，搜索框不会固定，会随着滚动）

不知道我是否表达明白没有

**Comment by markh5** [comment]
排查了一圈，终于发现了问题，正是因为我把外层.vue-treeselect__menu的max-height设置为none，导致它被子级撑开，而刚好我设置flex:1的块设置了overflow-y: auto，所有搜索框随着滚动一起被顶了上去。

请问作者有提供展开菜单禁止搜索框focus的参数吗？

**Comment by riophae** [comment]
是这个样子的，其实跟是否展开了某个节点没有关系，你去看代码的话会发现，凡是跟点击相关的操作，无论点到哪里，基本都会触发 `focusInput()`，然后输入框就得到焦点了。这个是非常必要的一个设计，对用户体验有好处。比如你可以想象下，用户点了 menu 里某个地方后，想再次输入还得再点一下输入框，会显得有些麻烦。

我想问题在于，原本你是希望输入框固定显示在顶部的，不随着下面 menu 一起滚动。每次自动 focus 的时候，如果因为向下滚动过输入框不在可见区域内的话，focus 后输入框必须显示出来，所以浏览器自动做了滚动，就跳到顶部去了。应该是这个逻辑。

那么我们能不能想办法，解决输入框不能固定在顶部显示的问题？这才是根源吧。

**Comment by riophae** [comment]
所以还是得覆盖 vue-treeselect 的样式……
