### ISSUE TITLE
list scrolls erratically on hover

### ISSUE THREAD

**Issue by wickkidd** [riophae/vue-treeselect#107]
I think this might be related to https://github.com/riophae/vue-treeselect/commit/461a5f1885becebbb9153f60e04a052854a35ee0

While the keyboard works well with the list, when you hover with the mouse, the list scrolls erratically and winds up at the bottom most of the time. It seems to trigger when hovering near the top of the bottom of the visible list. In both cases it scrolls down (toward the bottom). It never scrolls up unless you use the mouse wheel.

**Comment by riophae** [comment]
Hi! Just release v0.0.29. Hoping it has fixed.

**Comment by wickkidd** [comment]
That did it. Thanks again!
