### ISSUE TITLE
使用 loadOptions 没有触发方法

### ISSUE THREAD

**Issue by fairyly** [riophae/vue-treeselect#108]
我是想点击一个节点的左侧三角,然后异步加载子节点;使用 loadOptions

数据用的这类:
categoryOptions: [ {
      key: 'a',
      name: 'a',
      subOptions: [ {
        key: 'aa',
        name: 'aa',
      } ],
    } ],

引入:
<treeselect
            :value="category"
            :options="categoryOptions"
            :normalizer="normalizer"
            :default-expand-level="1"
            placeholder="所有品类"
            noOptionsText="暂无数据"
            noResultsText="无数据"
            no-children-text="无数据"
            :load-options="loadOptions"
            @select="categorySelect"
            />

 loadOptions({ action, parentNode, callback }) {
      console.log(action,parentNode)// 这里就没有打印,应该是没有触发这里方法
})

**Comment by riophae** [comment]
如果需要异步加载子节点，那么父节点的 `children` 属性应该设为 `null`，对应你这个情况就应该是 `subOptions: null` 这样

**Comment by fairyly** [comment]
@riophae 感谢
