### ISSUE TITLE
无法展开的问题

### ISSUE THREAD

**Issue by wangzhiman** [riophae/vue-treeselect#115]
![disk](https://user-images.githubusercontent.com/12542854/42025081-52beccbc-7af6-11e8-9068-e9ad015c634b.gif)

**Comment by riophae** [comment]
指的是菜单显示不完整对吗？我没能重现。我观察了下，发现 vue-treeselect 菜单的下边缘刚好是和背景重合了：

![image](https://user-images.githubusercontent.com/1289884/42051553-fb2988ea-7b3e-11e8-9884-8268f2f90f2e.png)

所以我猜测，可能是下面这个列表的某个容器元素加了 `overflow: hidden` 导致的？
