### ISSUE TITLE
Is there a way to expand all children of all root options?

### ISSUE THREAD

**Issue by zenchanhk** [riophae/vue-treeselect#118]
Hi,

I'm wondering it is possible to expand all children of all root options at the very first, which means we can see all options before selecting? Thanks.

**Comment by zenchanhk** [comment]
`defaultExpandLevel` is used for that purpose. I will close this issue.

**Comment by MikeMnD** [comment]
Is this working on latest version... seems strange:

`    _this15.$set(normalized, 'isExpanded', typeof isDefaultExpanded === 'boolean' ? isDefaultExpanded : level < _this15.defaultExpandLevel);`

with:

`<treeselect name="groups[]" :multiple="true" :defaultExpandLevel="Infinity" :flat="true"`

doesnt seem to work and only show 1 root level instead all 5 sub levels with items.
