### ISSUE TITLE
你好，麻烦问个问题

### ISSUE THREAD

**Issue by cotv** [riophae/vue-treeselect#119]
我们开发有客服组，不同组间可能有人员的重复，但是这个选择会debugger，有什么办法能不报错吗？或者配置项
[Vue-Treeselect Warning] Detected duplicate presence of node id 66196

**Comment by riophae** [comment]
这个唯一的办法就是，不让 id 重复，因为如果有 id 重复，vue-treeselect 也不能正常运行的，很容易出错

**Comment by allenGKC** [comment]
同遇到这个问题，页面上面多个组件需要用同一个options，请问有什么办法解决吗

**Comment by yongshangmoli** [comment]
请问，为了让id不重复，把它拼成了xx@xx的样子，这样之后已经选中的节点不会点开输入框不会自动选中了，是什么原因呢，有遇到同样问题的吗

**Comment by HenryAveMedi** [comment]
I have a project where nodes have multiple parents and need to be shown in tree in the different positions, if repeated it works actually properly, it selects or deselects the nodes in all instances (as it should). In my project is not an error/warning, can i deactivated the console.log somehow so i stop getting these warnings please?
thank you @riophae
