### ISSUE TITLE
Dropdown 被覆盖了

### ISSUE THREAD

**Issue by zenchanhk** [riophae/vue-treeselect#120]
您好！当我和vue-grid-layout一起使用时，如果dropdown太长的时候，会被另外一个GridItem所覆盖。vue-antd-ui的Select则没有此问题，请看附图。
[<a href='https://postimg.cc/image/51gsrieon/' target='_blank'><img src='https://s15.postimg.cc/51gsrieon/bug.png' border='0' alt='bug'/></a>](url)

**Comment by riophae** [comment]
刚刚看了下，原因很可能是 vue-antd-ui 默认把 menu 放到了 `document.body` 下面了，优先级比较高，所以就没有出现遮挡的问题。现在 vue-treeselect 确实缺少这个功能，正在开发中。再等一下哈。

**Comment by zenchanhk** [comment]
谢谢啦！
