### ISSUE TITLE
Input event is emitting on each options update

### ISSUE THREAD

**Issue by zikolach** [riophae/vue-treeselect#122]
Not sure if it a bug or feature, but for my use case I have to update options list after user select one or more available (as update I mean changing some parameters of node not relevant to tree select).

The problem is when options are updated - tree select component always emits new input event even if selected options list stays the same.

Basically internalValue has same list of options so calling `quickDiff` before emitting `input` event might be enough.

[Pen](https://codepen.io/zikolach/pen/dKEaOr?editors=1011)

P.S.: thanks for great component!

**Comment by riophae** [comment]
This is bug. Thanks for feedback!

**Comment by zikolach** [comment]
@riophae would you mind to publish npm package having latest changes?

**Comment by riophae** [comment]
v0.0.32 just released.
