### ISSUE TITLE
当层级vue-treeselect__indent-level-8 大于8时

### ISSUE THREAD

**Issue by TingRong-Pu** [riophae/vue-treeselect#125]
当层级vue-treeselect__indent-level-8 大于8时 vue-treeselect__indent-level-9 以上的层级会和vue-treeselect__indent-level-8并列显示   没有缩进的效果，请问是您这样限制了吗？

**Comment by riophae** [comment]
是的，如果需要支持更高层级的话，可以自行编译 LESS，覆盖掉 `@treeselect-max-level` 这个变量。但是一般不建议层级过深。

**Comment by TingRong-Pu** [comment]
好的  谢谢 我也很赞同你的建议  但需求方要求过于强力
