### ISSUE TITLE
异步加载问题以及unknown问题

### ISSUE THREAD

**Issue by zhangyinglei** [riophae/vue-treeselect#126]
<treeselect
          :options="data2"
          :load-options="loadOptions"
          placeholder="Try expanding any folder option..."
          v-model="orgData.parentOrgName"
          :normalizer="normalizer"
          />

data2:[],
        normalizer(node) {
          return {
            id: node.id,
            label: node.name,
            children: null
          }
        },

 loadOptions({ action, parentNode, callback }) {
      // Typically, do the AJAX stuff here.
      // Once the server has responded,
      // assign children options to the parent node & call the callback.
      // We just use `setTimeout()` here to simulate an async operation
      // instead of requesting a real API server for demo purpose.

      if (action === LOAD_CHILDREN_OPTIONS) {
         this.$http.get('url?id='+parentNode.id).then(({data})=>{
              if(data.code==200){
                 setTimeout(() => {
                    parentNode.children = data.data
                    console.log(parentNode)
                    callback()
                  }, 500);
              }else{
               
              }
               
            })
      }

自定义键的问题吗？？二层数据加载不了  显示没有可选项   还有初始数据如果为空时  会显示unknown   接收的字符串是父级元素传过来的时候  后面也会跟unknown

**Comment by zhangyinglei** [comment]
<treeselect
          :options="data2"
          :load-options="loadOptions"
          placeholder="Try expanding any folder option..."
          v-model="orgData.parentOrgName"
          :normalizer="normalizer"
          />

**Comment by zhangyinglei** [comment]
<treeselect
          :options="data2"
          :load-options="loadOptions"
          placeholder="Try expanding any folder option..."
          v-model="orgData.parentOrgName"
          :normalizer="normalizer"

**Comment by tangchuanxi** [comment]
我觉得load-options 中的callback 可以添加一个参数，传入一个callback供用户调用 解决unknown的问题
