### ISSUE TITLE
appendToBody新参数需要和z-index结合设置可能才有效

### ISSUE THREAD

**Issue by lerit** [riophae/vue-treeselect#127]
这个新设置我测试了，一般情况下没问题，但是当这个组件放到一个对话框组件中时，可能因为低于对话框z-index导致还是看不到。
之前我pull request时，也发现有这个可能性，于是加了一个对外暴露z-index的参数，
谢谢

**Comment by riophae** [comment]
谢谢反馈！我之前犹豫的结果是不加这个参数……现在看来还是得加上。

**Comment by riophae** [comment]
v0.0.33 已发布

**Comment by 931596973** [comment]
感谢，亲测有效
