### ISSUE TITLE
Delayed Loading: Normalising Children

### ISSUE THREAD

**Issue by Alig96** [riophae/vue-treeselect#128]
I am currently trying to work out how delayed loading works in the newer versions of this project. Before children were assigned via the callback, were also being normalized by the normalizer. However that seems like it doesn't work any more.

So if I am loading "children options" the children of those nodes are not being normalised. How can I normalise them using the "loadOptions" prop?

Here is the general code:
(note: i am overriding the parentNode with a normalized version, but its children are not normalized)
```
if(action === LOAD_CHILDREN_OPTIONS) {
//ajax here

parentNode = this.normalizer(childrenTagResponse.data)

callback()
}
```

**Comment by riophae** [comment]
vue-treeselect will always normalize any node you pass to it. Say your data structure of a branch node is like: 

```json
{
  key: '<id>',
  name: '<label>',
  subOptions: [ ... ],
}
```

Then what you should do is:

```js
if (action === LOAD_CHILDREN_OPTIONS) {
  //ajax here

  // simply use `subOptions` instead of `children`, vue-treeselect will take care about this
  parentNode.subOptions = childrenTagResponse.data

  callback()
}
```

**Comment by Alig96** [comment]
Since my server doesn't return a "children" or "suboptions" key as a response regardless of if it does has children or it doesn't, it returns a key boolean of "isBranch". Before I was adding the "children = null" to my normaliser, but now I am now just mapping over the response to add the nulled key from the server data instead.

```
        this.options = rootTagResponse.data.map(function(tag) {
          if (tag.isBranch) {
            tag.children = null;
          }
          return tag;
        });
```

Now it is working as expected. My fault for trying to do it within the normaliser rather than just on the response and then passing that to it.
