### ISSUE TITLE
Prevent Combining Nodes

### ISSUE THREAD

**Issue by Alig96** [riophae/vue-treeselect#13]
Although its a cool feature, is there a way to disable the combining of nodes into the parent node? I would like to keep them all as leaf nodes.

For example on the teaser image on the read me, If you select "Apple, Grapes, Pears" I would like to keep them all as leafs instead of combining them into the "Fruit" parent.

How can I disable this?

**Comment by t93c** [comment]
Have you tried using [flat mode](https://riophae.github.io/vue-treeselect/#flat-mode-and-sorting-value)?

**Comment by riophae** [comment]
Hi! This feature finally landed in v0.0.15. Check out the docs here: https://vue-treeselect.js.org/#prevent-value-combining

**Comment by Alig96** [comment]
Awesome, thank you very much for the awesome project! Keep it up!
