### ISSUE TITLE
Wrong item selected as value

### ISSUE THREAD

**Issue by shaffe-fr** [riophae/vue-treeselect#131]
Hello,

In the following pen : https://codepen.io/anon/pen/KBgzwV
I have a tree with a parent with a child and a grandchild.
When I click on the grandchild:
* The parent, child and grandchild are selected as expected, 
* The selected value is the child and not the grand child.

Is-it a configuration problem?

Thank you,

Karel

**Comment by riophae** [comment]
Maybe you need to use: `<treeselect value-consists-of="LEAF_PRIORITY" ... />`

See: https://vue-treeselect.js.org/#prevent-value-combining

**Comment by shaffe-fr** [comment]
Thank you for your quick reply.
LEAF_PRIORITY reverse the behavior expected.
If the parent has two grandchildren, the behavior is okay:
https://codepen.io/anon/pen/OwRNYN*

**Comment by shaffe-fr** [comment]
I didn't manage to find to right checkbox selection pattern: I wanted to check and get values of the clicked item and its parents.
I will use the flat option. 
Thanks

**Comment by riophae** [comment]
I'm sorry... I didn't get your point. Can you explain more about your expectation?

**Comment by shaffe-fr** [comment]
Yes sure!
I'm using the component for categories.
So for the following tree:
```
cat 1 === cat 1.1 === cat 1.1.1
      === cat 1.2
cat 2
```
If I check cat 1 or any root category, I only want the root to be selected.
If I check cat 1.1, I only want cat 1 and cat 1.1 to be selected (in the codepen, cat 1.1.1 is also selected).
If I check cat 1.1.1, I want cat 1, 1.1 and 1.1.1 to be selected. 
If I check cat 1.2, I want both cat 1 and cat 1.2 to be selected.

In every case, I want the values of every selected item. That behavior is nearly achieved with value-consists-of="ALL". The only problem is that the root value is not added when the clicked item is a child.

Thanks

**Comment by riophae** [comment]
This is very interesting. I think there should be a new option for this.

Thanks for your feedback!

**Comment by riophae** [comment]
The new option will be based on current `flat` prop. The difference is that, whenever the user clicks on a node, vue-treeselect should automatically select its ancestors. I think this is what you want.

**Comment by riophae** [comment]
Yeah, absolutely. 
And a new problem just came to my mind. What's the behavior you want when user deselects a node?
For example, the user first clicked on cat 1.1, then cat 1.1 & cat 1 should be both selected. Next if the user deselected cat 1.1 or cat 1, what should happend? Should vue-treeselect auto deselect its descendants?

**Comment by shaffe-fr** [comment]
I think that the general rule is that a child cannot be selected if its parents are not.
So when cat 1 and 1.1 are selected, if the user clicks 1 then both should be deselected. However, if the user deselects 1.1 both ways are possible but I would prefer that it deselects both as well.
What do you think?

**Comment by riophae** [comment]
There is no anwser. Just what you want and what is possible to be implemented. 

With cat 1 & cat 1.1 both selected:

- User deselects cat 1, automatically deselect cat 1.1 -> this is easy.
- User deselects cat  1.1, automatically deselect cat 1 -> this is a bit more complex. Since you also need to consider if there is other cat 1.x options being selected. After cat 1.1 being deselected, cat 1 still has other descendants selected.

Actually both are possible. But I want a intuitive API design, this is not easy.

**Comment by shaffe-fr** [comment]
You are right for the second case, if there are several sub-trees, the root should switch from X to - before being while it has some child selected. It's already what is happening [here](https://codepen.io/anon/pen/KBgzwV) if you check aa and ab, and then only unselect aa: a switch from X to -.

In order to make deep trees more flexible, I wonder if it wouldn't be better to only deselect 1.1 and not 1 when deselecting 1.1.

**Comment by riophae** [comment]
For now my planning is to add four new props.

- `autoSelectAncestors`
- `autoSelectDescendants`
- `autoDeselectAncestors`
- `autoDeselectDescendants`

With `autoSelectAncestors=true` & `autoDeselectDescendants=true`:

- When user selects cat 1.1, cat 1 will be automatically selected
- When user deselects cat 1, cat 1.1 will be automatically deselected (if it was selected). This also deselects cat 1.2 if applicable.

These all default to `false` and only apply to `flat` mode. The names may be subject to change.

**Comment by shaffe-fr** [comment]
Perfect, in flat mode, both ways can be done.

**Comment by riophae** [comment]
Landed in v0.0.33.
