### ISSUE TITLE
拖动了弹出层，下拉框的位置不会改变

### ISSUE THREAD

**Issue by languanghao** [riophae/vue-treeselect#132]
跟element ui的弹出层一起使用，如果弹出层拖动后，下拉框的位置还在原来的地方，导致错位

初始的时候一切正常
![default](https://user-images.githubusercontent.com/3765379/42918762-83eca218-8b41-11e8-9cd4-1879e9e48e1a.png)

拖动了一下弹出层位置后
![default](https://user-images.githubusercontent.com/3765379/42918776-84f7dff6-8b41-11e8-884d-eca82be2ebd6.png)

**Comment by languanghao** [comment]
@riophae 感谢提供了这么一个好用的插件

https://jsfiddle.net/xwczov8f/ 这个是element ui的例子，点后面那个 `打开嵌套表单的 Dialog` 按钮，好像他们那个不受滚动条影响

**Comment by riophae** [comment]
刚刚看了一下，他这个似乎就是监听了 `scroll` 事件……

**Comment by riophae** [comment]
刚刚发布了 v0.0.35，已经修正了，支持到 IE9。现在当用户操作时，比如选择选项（导致输入框尺寸变化、下拉框尺寸变化）、滚动页面或者缩放窗口，菜单的定位和展开方向都会重新计算。这样可以保证始终正确显示。
