### ISSUE TITLE
Can we have the node items to be single select and leaf items to be multi-select?

### ISSUE THREAD

**Issue by kishankarun** [riophae/vue-treeselect#134]
Hi,

I have a requirement where I want to have the user to select only one of the tree (parent) nodes but one or more of the child nodes.
* Node
  - [x] Leaf 1
  - [x] Leaf 2
  - [x] Leaf 3

Is it possible by any way?

**Comment by riophae** [comment]
Hi! You can try this:

```vue
<template>
  <treeselect ref="treeselect" :options="options" :multiple="true" :flat="true" v-model="value" />
</template>

<script>
  export default {
    data: {
      value: [],
      options: [ {
        id: 'a',
        label: 'a',
        children: [ {
          id: 'aa',
          label: 'aa',
        }, {
          id: 'ab',
          label: 'ab',
        } ],
      }, {
        id: 'b',
        label: 'b',
        children: [ {
          id: 'ba',
          label: 'ba',
        }, {
          id: 'bb',
          label: 'bb',
        } ],
      } ],
    },

    watch: {
      value() {
        const { treeselect } = this.$refs
        let branchNodesCount = 0
        // Reverse the array first, we only want the last branch node
        const newValue = this.value.slice().reverse().filter(id => {
          const node = treeselect.getNode(id)
          if (node.isLeaf) return true
          if (branchNodesCount++ > 0) return false
          return true
        }).reverse()
        // Only assign new value when there were more than one branch nodes checked
        // Otherwise we could run into infinite loop
        if (branchNodesCount > 1) this.value = newValue
      },
    },
  }
</script>
```

And here is a live demo: https://codepen.io/riophae/pen/wxmbOL

**Comment by kishankarun** [comment]
Thanks for the code @riophae 

But in this case,

1. If leaf node (aa) of node (a) is selected and when I change the node from a to b, corresponding children are not getting selected --> Which got fixed when I changed the property flat to false

2. This didn't work when one of the child nodes only is selected and I change the parent node
(Due to this, it will not work when I have one of the children disabled)

3. This didn't work when 
`:value-consists-of="'ALL_WITH_INDETERMINATE'" `

https://codepen.io/kishanka/pen/xJjwdj



(Coz, I would like to know the parent (and grandparent) of any leaf node, when only a leaf node is selected. That's why I have  `:value-consists-of="'ALL_WITH_INDETERMINATE'" `

**Comment by riophae** [comment]
Given:

```
- [x] a
      - [x] aa
      - [ ] ab
- [ ] b
      - [x] ba
      - [ ] bb
      
```

Then check "b". we'll get

```
- [ ] a
      - [ ] aa
      - [ ] ab
- [x] b
      - [ ] ba
      - [ ] bb
```

Am I understanding it right? :)

**Comment by kishankarun** [comment]
Hi @riophae ,

As per my requirement,

Given:

- [x] a
      - [x] aa
      - [ ] ab
- [ ] b
      - [x] ba
      - [ ] bb
      
Then check "b". we'll get

Given
```
- [-] a
      - [x] aa
      - [ ] ab
- [x] b
      - [ ] ba
      - [ ] bb
```
Then check b, we should have all sub items of b selected.

```
- [ ] a
      - [ ] aa
      - [ ] ab
- [x] b
      - [x] ba
      - [x] bb
```

**Comment by kishankarun** [comment]
Thanks @riophae ,

This is almost what I wanted...

When the parent node is unchecked, i don't want any child nodes to be selected, which is happening in this code pen you sent.

![image](https://user-images.githubusercontent.com/323202/43758138-d15f4acc-9a38-11e8-8f72-06881e6c7b23.png)


------
When I change from flat = false, I couldn't solve it

Please find below

![image](https://user-images.githubusercontent.com/323202/43758211-080f9360-9a39-11e8-89f2-0ecece781aca.png)

When i click on the parent node `b`, this is what happens

![image](https://user-images.githubusercontent.com/323202/43758258-2b1452ce-9a39-11e8-9dc3-152bd103c6d1.png)

**Comment by riophae** [comment]
I see. You can use `autoDeselectDescendants` prop.

https://codepen.io/riophae/pen/OwooLq

**Comment by kishankarun** [comment]
Great! Thanks for your quick response, @riophae , it works ! :)

**Comment by kishankarun** [comment]
But this issue still exists - please check the selected items (bb, ba and bb again)

![](https://user-images.githubusercontent.com/323202/43758258-2b1452ce-9a39-11e8-9dc3-152bd103c6d1.png)

**Comment by riophae** [comment]
You should use float mode...

**Comment by kishankarun** [comment]
sorry , probably my bad, as you mentioned in the documentation, `autoDeselectDescendants ` works only for flat mode.

In your codepen, i was trying with flat mode = false . That works.

Thanks :)

**Comment by ducvietsqt** [comment]
@kishankarun 
I was update watch function of @riophae 
That's work right?
` watch: {
      value() {const {treeselect} = this.$refs
                // todo case 1
                if (!this.value || !this.value.length || this.value.length === 1) return;
                // todo case 2
                let lastValue = this.value.slice().reverse()[0]
                let prevLastValue = this.value.slice().reverse()[1]

                let nodeLastValue = treeselect.getNode(lastValue)
                let nodePrevLastValue = treeselect.getNode(prevLastValue)
                // node branch
                if (nodeLastValue.children) {
                    return this.value = [lastValue]
                }
                // todo case 3
                console.log({
                    nodeLastValue: nodeLastValue.parentNode,
                    nodePrevLastValue: nodePrevLastValue.parentNode
                })
                if(nodeLastValue.parentNode !== nodePrevLastValue.parentNode) {
                    return this.value = [lastValue]
                }}
`
