### ISSUE TITLE
Is it possible to dynamically select disabled sub-item (leaf) when the parent node is selected?

### ISSUE THREAD

**Issue by kishankarun** [riophae/vue-treeselect#135]
Hi,

I have a parent node, some of whose nodes are disabled.
Is there a way that when I select the parent, its children (including the disabled ones) are selected?

**Comment by riophae** [comment]
Hi, currently this is not possible. Can you explain more about your requirement?

**Comment by kishankarun** [comment]
Hi @riophae , thanks for the reply.

The requirement is like below:

I have one (or more) disabled leaf nodes, which are unchecked by default.
I want the leaf nodes to be checked only when its parent node is selected.

![image](https://user-images.githubusercontent.com/323202/43569349-d2b5a58e-9654-11e8-9a59-ea1e284f4945.png)

I want this option as I want to restrict the user to select the disabled items, but want it to be selected if he selects the parent node.

Actually I want all the disabled nodes to be checked, even when any of the other leaf nodes are selected too... , which is my actual requirement

**Comment by riophae** [comment]
I think there could be a new option :) Thanks for your feedback.

**Comment by kishankarun** [comment]
Hi @riophae , 
You are welcome :smile: 

I tried this and was able to do this in watch, by updating the `value` with the required nodes by looping through them.

Please find the code below:
But it is still not complete, as here I am unable to deselect it..
Could you please help?

https://codepen.io/kishanka/pen/ejrGqB

**Comment by riophae** [comment]
I'm sorry, but I have to say better don't use watch, since it would make it much more complex :) It doesn't need to be like that. Please be patient, I'll add a new option for this asap.

**Comment by kishankarun** [comment]
Hi @riophae ,

Thanks.

**Comment by riophae** [comment]
Just released v0.0.36.
