### ISSUE TITLE
change text style

### ISSUE THREAD

**Issue by maggiew61** [riophae/vue-treeselect#136]
hi Fangzhou Li, 

first of all, thank you for this awesome plug-in. I really appreciate it
I would like to know how to change the styling of the dropdown texts.  I would like to be able to increase the text font size and its color from grayish to black. 
I tried to find the styling of these texts in the vue-treeselet.css but was no success. Can you kindly point to me which parts of the css on vue-treeselect.css is associated with the styling of the dropdown texts? 

Thanks again

**Comment by riophae** [comment]
Hi, you can customize the dropdown style by:

```css
.vue-treeselect__menu {
  color: black;
}
```

**Comment by maggiew61** [comment]
hi riophae, 
thanks for the quick reply. 
I tried adding this to my code
    /deep/.vue-treeselect__menu{
              outline:5px solid red;
              color: red;
            }
but it only gave me the following. I still don't know how to change the grayish texts to black and bigger 

![2018-08-03_1531](https://user-images.githubusercontent.com/25575482/43630364-ad208bc0-9732-11e8-8df6-ec10d27c6008.png)

Thanks again!

**Comment by riophae** [comment]
I see. Maybe you should try this:

```css
label.vue-treeselect__label {
  color: black;
}
```

**Comment by maggiew61** [comment]
hi @riophae thanks for the quick reply

the code below still can't change the text color 
`label.vue-treeselect__label {
  color: black;
}`

however, I tried increasing the font size 
`/deep/ .vue-treeselect__menu{
        font-size:20px;
    }`
![2018-08-06_1336](https://user-images.githubusercontent.com/25575482/43698669-c30f0e14-997d-11e8-9a67-c9b96e7f1f96.png)

and it resulted in bigger space between the rows so this is ideal, even through I still can't change the text color but this is good now. thanks @riophae

**Comment by mrmyn** [comment]
我加上appendtobody后也遇到下拉选项样式被冲掉的问题。。。。现在使用label.vue-treeselect__label得到了解决，前来感谢！！

**Comment by parthobepary** [comment]
it's not work on nuxt3js
