### ISSUE TITLE
在 vue 插件中引入插件,报错找不到该插件模块

### ISSUE THREAD

**Issue by fairyly** [riophae/vue-treeselect#138]
自己写了一个插件,写的插件中引入了一个插件@riophae/vue-treeselect",发布到npm 服务器后,
项目中引入报错
Cannot find module "@riophae/vue-treeselect"

**Comment by riophae** [comment]
应该是 `package.json` 里依赖漏掉了吧？

**Comment by fairyly** [comment]
@riophae 

我插件里 的依赖都有的额
"dependencies": {
    "@riophae/vue-treeselect": "0.0.35",
    "axios": "^0.18.0",
    "vue": "^2.5.11"
  }

**Comment by riophae** [comment]
好的 你的插件名字是什么？我可以试一下吗

**Comment by fairyly** [comment]
写的插件中这么引入是不是不对?

import Treeselect from '@riophae/vue-treeselect'
  // import the styles
  import '@riophae/vue-treeselect/dist/vue-treeselect.css'

这个插件写好后,发布 到npm ,之后在项目中引入, 就报没找到这个模块

**Comment by fairyly** [comment]
@riophae 稍等,我改下源,插件发布在我们公司私有npm服务器上了

**Comment by fairyly** [comment]
@riophae 抱歉上午打包一直有些问题

**Comment by fairyly** [comment]
@riophae https://www.npmjs.com/package/test-people

```
npm i test-people
```

**Comment by fairyly** [comment]
应该是我插件上午打包的问题,谢谢
