### ISSUE TITLE
希望增加一个功能点

### ISSUE THREAD

**Issue by mythbobo** [riophae/vue-treeselect#14]
:flat="true"是父节点，子节点都会作为选择项,
希望能增加elementUi的tree那样的功能，只取叶子节点的作为选择项。

**Comment by riophae** [comment]
你好，很抱歉回复晚了！
这个功能目前已经提供了，你可以使用 `disableBranchNodes: true`，文档在这里：https://vue-treeselect.js.org/#disable-branch-nodes
