### ISSUE TITLE
Align vue-treeselect with a label

### ISSUE THREAD

**Issue by IvoPereira** [riophae/vue-treeselect#141]
Hello.

I am trying to align vue-treeselect side-by-side with other elements however I am probably missing something. The only way I've been able to this to work was specifying a custom max-width property, so the rest of the elements on its side would not get overlapped.

The issue can be seen in the following snippet, as I am trying to align two elements (a simple span and a vue-treeselect):
https://codesandbox.io/s/8z0wzpxmxj

Any idea?

**Comment by riophae** [comment]
Hi @IvoPereira. I'm sorry but not seeing any issue or maybe not getting the point. Can you explain more or improve your demo? I don't know how you want the elements to be aligned.

![image](https://user-images.githubusercontent.com/1289884/43849027-f7ceeefe-9b66-11e8-82bb-91c2b039d325.png)

**Comment by IvoPereira** [comment]
@riophae I want the elements to be side-by-side.

Let me know if this helps to understand the issue:
https://codesandbox.io/s/8z0wzpxmxj

**Comment by riophae** [comment]
I see. You should use `table-cell` instead of `inline-block`:

https://codesandbox.io/s/mzv9npov48
