### ISSUE TITLE
scrolling IE-11

### ISSUE THREAD

**Issue by borisbutenko** [riophae/vue-treeselect#15]
Hello, guy, i have a small problem:

- i dont scroll in IE 11 on scrollbar click (dropdown closed when i clicking on scrollbar)

Do u fix it ?

**Comment by lwidotnet** [comment]
See https://github.com/riophae/vue-treeselect/pull/38 ...

**Comment by riophae** [comment]
I have successfully reproduced the bug on IE 11.

**Comment by riophae** [comment]
A similar issue of another select component: https://github.com/selectize/selectize.js/issues/182

**Comment by riophae** [comment]
I think this would be helpful: https://github.com/bbc/selectize.js/commit/3275c4f1cf80977fc7972abef0431292646e8ba6
