### ISSUE TITLE
请问如何取消“No sub-options”的提示

### ISSUE THREAD

**Issue by Javi101** [riophae/vue-treeselect#152]
因为数据在无子节点时 返回的是“Array(0)”，导致"No sub-options"提示频繁显示

**Comment by WiFiUncle** [comment]
没有子节点就直接删除children、、、

**Comment by sgf** [comment]
@Javi101 楼上的意思 估计应该是数据源 直接不要给 children:[] 这个成员 也不要 children:null 
直接不给

**Comment by garyganyang** [comment]
如果树的深度不一样 还得递归delete children, 不方便
