### ISSUE TITLE
defaultExpandLevel can't be updated after initialization

### ISSUE THREAD

**Issue by dermansi** [riophae/vue-treeselect#154]
Hey,

first of all: great work, we really like your component.

We have to change the default expand level depending on a few other options but it seems like the component doesn't respect changes to that prop after init. Is there any other way to re-set the defaultExpandLevel after init?

Thanks
dermansi

**Comment by riophae** [comment]
Hi! `defaultExpandLevel` is designed to be respected only on first init. Changing its value won't work as what you expect.

However, you can manually set the expanded state of each node by:

```vue
<template>
  <div id="app">
    <treeselect ref="treeselect" ... />
  </div>
</template>

<script>
  export default {
    methods: {
      setExpandLevel(level) {
        const { treeselect } = this.$refs

        treeselect.traverseAllNodesByIndex(node => {
          if (node.isBranch) {
            // note that `level` is zero-based
            node.isExpanded = node.level <= level
          }
        })
      },
    },
  }
</script>
```

**Comment by dermansi** [comment]
Thank you!
