### ISSUE TITLE
我应该如何重新渲染Treeselect? (how to rerender the Treeselect)

### ISSUE THREAD

**Issue by LoopSun** [riophae/vue-treeselect#16]
- template
```
<treeselectid='xxx' v-if="modalShow">...</treeselect>
<button @click="rerender"></button>
```
- script
```
rerender: function(){
    this.modalShow = false;
    this.modalShow = true;
}
```

这个方法貌似无效(this method is useless)
或者换而言之，我应该如果在treeSelect的一个生命周期中动态的更改option值, load-root-option只会监听第一次左键点击(in other words, how I can do that I can change the option in  dynamic within the 
treeselect whole life cycle )

**Comment by chenEdgar** [comment]
可以查看源文件，通过ref应用treeselect组件，调用组件内部的initialize([]), 实现动态更改值。
如：
 `this.$refs.tree.initialize(filterData)`

**Comment by lovebslq** [comment]
这真是太漂亮了 @chenEdgar  刚接触VUE，这个困扰我好些天，谢谢你

**Comment by riophae** [comment]
@LoopSun @chenEdgar @lovebslq Hi all! A new version just released, please check out: https://github.com/riophae/vue-treeselect/issues/63#issuecomment-382154000
