### ISSUE TITLE
Doesn't support rtl

### ISSUE THREAD

**Issue by HamidOsouli** [riophae/vue-treeselect#162]
First of all thank you for this great package.
Is there some way to do this with **rtl** ?
I put text-align to right but this does not work and turns to something like this : 
![untitled2](https://user-images.githubusercontent.com/20487800/45349618-07df6380-b5c7-11e8-9401-9dbf47e9e162.png)
as you can see the layout does not work..
thank you :)

**Comment by MostafaTech** [comment]
this pull request resolves the issue #269
