### ISSUE TITLE
Fix vulnerabilities found with npm audit

### ISSUE THREAD

**Issue by m-zuro** [riophae/vue-treeselect#186]
Hi,
Yesterday when I installed your package I've received msg "found 1 low severity vulnerability".
Here is the screenshot:

![screen shot 2018-11-08 at 09 45 10](https://user-images.githubusercontent.com/44112517/48190810-804e7080-e33b-11e8-9bb9-796e5e8bbfe6.png)

Can you fix this please? Thanks

**Comment by michelleLegend** [comment]
I'm getting the same, the lodash package needs to be updated. Here is a link to the advisory: https://www.npmjs.com/advisories/577.

**Comment by enhendrickson** [comment]
Same issue here; +1 for a fix.

**Comment by riophae** [comment]
Thanks for contribution! I'll release this ASAP.
Sorry for it takes so long!
