### ISSUE TITLE
能否自定每个节点的信息？

### ISSUE THREAD

**Issue by wangtifang** [riophae/vue-treeselect#19]
目前看文档每个节点包含：id，label。能否包含其他的信息？能否自定义字段名称？。例如：ID,Name，Icond等。最好把每个节点的信息处理为一个对象，对象里的属性就可以自定了。

**Comment by chenEdgar** [comment]
组件内的key可以是一个对象，所有的自定义的属性都可以放在这个key内。

基于本人的时间，放在key上不利于编辑（需要保证key内的值相同）

**Comment by riophae** [comment]
你好，刚刚更新了文档，关于每个节点中可以定义的信息请参考这里：https://vue-treeselect.js.org/#node
关于自定义字段，请问有什么具体的使用场景吗？如果是自定义图标的话，暂时还不支持，之后会加入的。
