### ISSUE TITLE
text filtering

### ISSUE THREAD

**Issue by stefan2410** [riophae/vue-treeselect#2]
Hi!  nice component!
In the example "Disabling Branch Nodes", if I press "fra", it does not display only the France. The same with other countries also.

**Comment by riophae** [comment]
Yeah, this is by design. 😃 Under the hood, it's [fuzzysearch](https://github.com/bevacqua/fuzzysearch) that is handling the filtering.
I think there should be a new option determining whether to turn on the fuzzy search.

**Comment by stefan2410** [comment]
Yes, probably, thanks.

**Comment by daniele8080** [comment]
Hi! nice component!
I would like to know it is possible to add also an icon like a folder image.
What property should I use?
Can you tell me how to do it? Should I use glyphicon?
Thank in advance!

**Comment by riophae** [comment]
@stefan2410 Hi, really sorry for it take so long to have the feature finished. Just to tell you that a new version including the `disableFuzzyMatching` prop is just released.
