### ISSUE TITLE
When use element-ui with size="mini" or "small", the .vue-treeselect__control canot be controlled

### ISSUE THREAD

**Issue by richwxd** [riophae/vue-treeselect#204]
As per the title, I have seen the el-input in mini size, the height is 28px. When I put the lines below, the treeselect was still the old style as 36px height. How to customize the treeselect with style or class? 
I know this library is very fantasitic, but it will be more better if can be customized.
.vue-treeselect__control {
    height: 28px !important;
}
.vue-treeselect__input-container {
    height: 26px !important;
}

**Comment by richwxd** [comment]
I have solved this problem with sort of "boring" way. Mannually copy treeselect.css and rename it, then modify the height. In the called vue, just import the my css instead of treeselect.css. Hope it resolves your samilar issue. :)

**Comment by Majid-Kamali** [comment]
Try this
```
div.vue-treeselect__control {
  height: 55px !important;
  background-color: var(--v-vue_treeselect-base) !important;
  border: none;
  border-bottom: 1px solid #949494 !important;
  border-radius: 3px !important;
}
div.vue-treeselect__placeholder {
  margin-top: 10px !important;
  color: #606060 !important;
}
div.vue-treeselect__single-value {
  margin-top: 10px !important;
  margin-right: 6px !important;
  color: #606060 !important;
}
div.vue-treeselect__menu {
  background-color: var(--v-vue_treeselect-base) !important;
}
div.v-treeview-node__label {
  border: 0.5px solid #827f7f;
  text-align: right;
  padding: 4px 30px;
  border-radius: 6px;
}

.vue-treeselect__menu-container{
  z-index: 100000;
}
```

**Comment by richwxd** [comment]
Yeah. There are many new UI components available. They have a "TreeSelect" component. Since they are native implementation of a UI suite, perhaps it is the right way to solve this issue. :)
