### ISSUE TITLE
How do I limit the length of the selected value?

### ISSUE THREAD

**Issue by lvwzhen** [riophae/vue-treeselect#223]
I wanted to limit the number of selected, but I only found the Settings that limit the display

![image](https://user-images.githubusercontent.com/2337506/53146161-1bfba800-35de-11e9-8e58-0ab5400442a4.png)
I want to alert and terminate it when I select 5 items, rather than just limit the number displayed.

Thank you

**Comment by sergor5** [comment]
I've done it like this:
 
`<treeselect  v-model="select_values" :options="fruits"   :multiple="true"  @input="handeTreeSelect">`

```
methods: {
    handeTreeSelect(data) {
      if (data.length > 3) {
           this.select_values.length = 3
      }
    },
}
```
