### ISSUE TITLE
menu 遮挡

### ISSUE THREAD

**Issue by xchz** [riophae/vue-treeselect#229]
![8TK1Y~BD`S$U_7P9U_WJA2O](https://user-images.githubusercontent.com/7054257/54598392-62281800-4a73-11e9-9531-569e16fa3628.png)
http://element-cn.eleme.io/#/zh-CN/component/collapse vue-treeselect和collapse 组合使用被遮挡了，应该不是menu的zindex问题

**Comment by xchz** [comment]
找到问题了，collapse有设置overflow: hidden；设置appendToBody为true 可以解决

**Comment by laienliang** [comment]
怎么解决的呢？我用el-tab也遇到一样的问题

**Comment by laienliang** [comment]
> 找到问题了，collapse有设置overflow: hidden；设置appendToBody为true 可以解决

您好，请问题是怎么解决的呢，我用el-tabs也遇到一样的问题，设置了z-index没有生效

**Comment by xchz** [comment]
答案不是写了吗，浪费时间奥
