### ISSUE TITLE
alwaysOpen and Edge CSS issues

### ISSUE THREAD

**Issue by crackernutter** [riophae/vue-treeselect#234]
Has anyone had issues with using alwaysOpen=true in MS Edge and having the nodes render strangely...?  I don't know what is happening here and can't figure out why.  If I click on the nodes, they suddenly render correctly - it's just when the component loads it is wrong
![Capture](https://user-images.githubusercontent.com/6819550/55016243-baf03700-4fc4-11e9-96c7-d4b8710c11f7.PNG)

**Comment by riophae** [comment]
Hi, I'm closing this since it has been a long time.
