### ISSUE TITLE
将vue-treeselect放在elementui 的el-table组件的el-table-column中无法显示下拉树形组件

### ISSUE THREAD

**Issue by SeaYang** [riophae/vue-treeselect#236]
如题，在elementui 的el-table组件的el-table-column中使用vue-treeselect，发现无法显示下拉项，
![image](https://user-images.githubusercontent.com/7547454/55322224-5a726580-54ae-11e9-9fd3-4cc7f1c254d5.png)

如果不放在el-table-column中，则是正常的
![image](https://user-images.githubusercontent.com/7547454/55322300-8a216d80-54ae-11e9-8840-4baaad67316c.png)

**Comment by YangChaoJie** [comment]
这个怎么解决的呀？

**Comment by mmorcc** [comment]
我也遇到了这个问题啊
