### ISSUE TITLE
多选时，点击已选值会删除该已选值

### ISSUE THREAD

**Issue by dhl28** [riophae/vue-treeselect#244]
动作：点击已选值
期望：展开下拉树
实际：展开下拉树，并且清除了该已选值

**Comment by Lensgcx** [comment]
同上

**Comment by Zuohao1994** [comment]
问题解决了嘛？

**Comment by yangxiyangxi** [comment]
这个确实是个坑，后来我想到了用css样式禁用选中的标签的点击，加了这个就好了.vue-treeselect__multi-value-label{
    pointer-events: none
  }
  .vue-treeselect__icon.vue-treeselect__value-remove{
    pointer-events: auto
  }

**Comment by yangxiyangxi** [comment]
上面复制漏了一点，应该是
.vue-treeselect__multi-value-item,.vue-treeselect__multi-value-label{
    pointer-events: none
  }
  .vue-treeselect__icon.vue-treeselect__value-remove{
    pointer-events: auto
  }

**Comment by riophae** [comment]
你好，这个就是故意这样设计的。如果确有需要的话，参照上面的方法应该可行。

**Comment by zwd862375698** [comment]
这样的话slot="value-label" 里面自定义的事件也不能触发了

**Comment by zwd862375698** [comment]
> 
这样的话slot="value-label" 里面自定义的事件怎么触发呢
