### ISSUE TITLE
import Treeselect from '@riophae/vue-treeselect';报错

### ISSUE THREAD

**Issue by yannanna0920** [riophae/vue-treeselect#250]
![image](https://user-images.githubusercontent.com/48897146/57993235-b8085300-7aea-11e9-8d69-3c1d5cd5f66b.png)
![yannan](https://user-images.githubusercontent.com/48897146/57993242-c0f92480-7aea-11e9-8bd5-926d9b1c3bf1.jpg)
谁知道这个引入报错是很么原因  实际是能使用的 但是inport 一直报红

**Comment by lcjnil** [comment]
这是 ts 的报错，因为这个模块没有类型。
可以加一个 `//@ts-ignore` 忽略一下

**Comment by yannanna0920** [comment]
> 这是 ts 的报错，因为这个模块没有类型。
> 可以加一个 `//@ts-ignore` 忽略一下

怎么加 ？直接在import 结尾加这个注释？  并没有效果  依然报红警告

**Comment by yannanna0920** [comment]
> 这是 ts 的报错，因为这个模块没有类型。
> 可以加一个 `//@ts-ignore` 忽略一下

已经知道了 谢谢~
