### ISSUE TITLE
Search closes on IE when scrollbar is clicked

### ISSUE THREAD

**Issue by kramcore** [riophae/vue-treeselect#252]
Still having issue with scrollbar closing the search when its clicked, seems like its been fixed but the fix doesn't seems to work?
#15

**Comment by kramcore** [comment]
I think `instance.closeMenu()` is not really necessary, as the instance will close anyway when user clicks away. It's whats causing the search to close when scrollbar is clicked.

**Comment by riophae** [comment]
I'm sorry! This was a regression and should be fixed again now.
