### ISSUE TITLE
nextTick: "TypeError: implementation is not a function"

### ISSUE THREAD

**Issue by dimasx010** [riophae/vue-treeselect#265]
Hello, i used your component for multiples selec, all ok..

but in event click, say ; 

> nextTick: "TypeError: implementation is not a function"
> <VueTreeselectMenu> at Menu.vue

the data send successfully but in console ever watch error

**Comment by riophae** [comment]
Can you give more information on this issue? I don't have a clue :/

**Comment by dimasx010** [comment]
Hello, the componet functions i'ts fine, only error is [Error in console](https://i.ibb.co/7KWvVp9/vuetree-error.png)
Laravel 5.3
Vue 2.
even with the example of the web the same thing happens
salu2, thanks

**Comment by riophae** [comment]
Can you use this [pen](https://codepen.io/riophae/pen/MExgzP) to create a demo? Otherwise, I'm afraid I can't help :/

**Comment by dimasx010** [comment]
i'm try in other projects and fine, no idea what is the problem, thanks...
i'm compiling with Gulp.

**Comment by tzcodingjs** [comment]
hello, I try to packaging a npm Secondary, the browser console show issus 
'[Vue warn]: Error in nextTick: "TypeError: implementation is not a function"'
