### ISSUE TITLE
Unknown custom element: <treeselect> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by skiy** [riophae/vue-treeselect#27]
![selection_015](https://user-images.githubusercontent.com/3362147/37023017-9b6bc37a-215f-11e8-8eeb-27ce9040afa5.png)
![selection_014](https://user-images.githubusercontent.com/3362147/37023018-9bafc516-215f-11e8-8f40-7097ec6418cc.png)

由于对webpack+vue不太熟悉，所以用了CDN方式，但是不知道应该怎么下手呢？这样做没有显示选择框。

**Comment by riophae** [comment]
你好，看样子你只是引入了组件的模块，但是没有把组件注册到 Vue 里面去，因此 Vue 在调用的时候找不到这个组件。

可以在 `new Vue({` 这一行前面加上：

```js
Vue.component('treeselect', VueTreeselect.Treeselect);
```
