### ISSUE TITLE
Error in v-on handler: "TypeError: Cannot read property '$refs' of undefined"

### ISSUE THREAD

**Issue by iliyaZelenko** [riophae/vue-treeselect#272]
Hi, thanks for component! 

I have error, I don't  know why.

My code:

```vue
<transition name="fade">
  <span
    v-if="showSelect"
    class="tag-select-tooltip"
    :style="tooltipStyles"
  >
    <treeselect
      :options="smartTags"
      disable-branch-nodes
      search-nested
      always-open
      show-count
      auto-focus
      @input="onSmartTagsSelectOnSelect"
    />
  </span>
</transition>
```

![image](https://user-images.githubusercontent.com/13103045/62012005-228fdc00-b189-11e9-970e-3e15d3ab36f3.png)

In this place:

![image](https://user-images.githubusercontent.com/13103045/62012043-b497e480-b189-11e9-8f4a-a3a287bbae01.png)
var isClickedOnValueContainer = this.getValueContainer().$el.contains(evt.target);
![image](https://user-images.githubusercontent.com/13103045/62012055-db561b00-b189-11e9-88fc-7f54c63a8ed6.png)

Everything works fine, despite the error.

**Comment by iliyaZelenko** [comment]
This happens after I select an item in the select. Note: select immediately hides after selection (`v-if`).

With `v-show` instead of `v-if` I don't have the error, but I need to use `v-if`.

**Comment by iliyaZelenko** [comment]
I created PR: https://github.com/riophae/vue-treeselect/pull/273

**Comment by riophae** [comment]
Hi, @iliyaZelenko. I think the better solution is hiding the input AFTER vue-treeselect has processed all the events it has listened to. vue-treeselect should always assume the `control` is being there since vue-treeselect itself never hides the control.

Do you have `this.showSelect = false` in your `onSmartTagsSelectOnSelect`? If so, I suggest changing it to:

```
this.$nextTick(() => {
  this.showSelect = false
}, 0)
```

**Comment by iliyaZelenko** [comment]
@riophae Thanks for the response. I already tried it, forgot to write about it.
[Here](https://codesandbox.io/s/aligning-vue-treeselect-with-a-label-323kn) is reproduction for you.

**Comment by riophae** [comment]
@iliyaZelenko Ah I'm sorry, I just tried changing it to `setTimeout` and it did the trick:

https://codesandbox.io/s/refs-error-w22gp

**Comment by iliyaZelenko** [comment]
@riophae Cool, it seems like a good solution, thanks!

**Comment by EkaterinaTaltseva** [comment]
Thank you for helping! moved the method to actions: {}  everything worked too! =)

**Comment by micdobro** [comment]
This is unfortunately still a problem. Solutions with `this.$nextTick()` or `setTimeout()` just play with time and might fix the race condition that happens there. 

I have the same treeselect widget used in several spots in the project - and in one of them it does complain about undefined refs. In other places it just works.

**Comment by SagarVishal** [comment]
For me i just put this.$refs.otherElement.focus() in  beforeDestroy() which solved the error as it closes the menu
