### ISSUE TITLE
反馈一个兼容性问题，单选且禁用模式下（ie11），不显示选中内容

### ISSUE THREAD

**Issue by qingyun1029** [riophae/vue-treeselect#274]
在官网上也发现这个问题，ie11测试下。用浏览器打开网址：https://vue-treeselect.js.org/ ， 找到`More Features` 小节，去掉`Multi-select`，并勾选`Disabled`会发现问题所在。

修改方式，覆盖样式（不知道是否会导致其他问题，暂未发现）：

```
.vue-treeselect--disabled .vue-treeselect__single-value{
  position: static!important;
}
```

**Comment by riophae** [comment]
谢谢反馈！确实是 bug，接下来解决一下
