### ISSUE TITLE
infinite scroll

### ISSUE THREAD

**Issue by yash-habilelabs** [riophae/vue-treeselect#275]
I want make infinite scroll under the single select . is there any way to achieve this ? any help will be appreciate.

**Comment by riophae** [comment]
In short, you can listen to `scroll` event of the menu element, and check if the scrollbar has scrolled to the end. If so, loading new options and then change the value of `options` prop.

You first need to set a ref for vue-treeselect:

```vue
<template>
  <vue-treeselect ref="treeselect" .../>
</template>
```

Then you can access the menu element by `this.$refs.treeselect.getMenu()` and bind a `scroll` listener to it. Note that every time the menu gets closed, the menu element will be destroyed. You need to bind the listener again.

To make this possible, you can:

```vue
<template>
  <vue-treeselect ref="treeselect" options="options" @open="handleMenuOpen" .../>
</template>

<script>
  export default {
    data: {
      options: [],
      fetchingOptions: false,
    },

    methods: {
      fetchOptions() {
        if (this.fetchingOptions) return
        this.fetchingOptions = true

        xhr().then(newOptions => {
          this.options.push(...newOptions)
          this.fetchingOptions = false
        })
      },

      handleMenuOpen() {
        const menu = this.$refs.treeselect.getMenu()

        menu.addEventListener('scroll', () => {
          if (hasReachedEnd) this.fetchingOptions()
        })
      },
    },
  }
</script>
```

**Comment by yash-habilelabs** [comment]
Thanks for the update @riophae.
i have tried above snippet, but getting TypeError: Cannot read property 'addEventListener' of null.
i don't know why, if not mind can you please help

**Comment by riophae** [comment]
Ah, my bad. It should be:

```js
...
handleMenuOpen() {
  // or setTimeout if $nextTick doesn't work
  this.$nextTick(() => {
    const menu = this.$refs.treeselect.getMenu()

    menu.addEventListener('scroll', () => {
      if (hasReachedEnd) this.fetchOptions()
    })
  })
},
...
```

**Comment by yash-habilelabs** [comment]
@riophae  the above snippet give the scroll event but can't get your 'hasReachedEnd'. if you can please clear then i can got the scenario easily.

**Comment by riophae** [comment]
This is how to compute `hasReachedEnd`:

```js
const hasReachedEnd = menu.scrollHeight - menu.scrollTop <= menu.clientHeight * 1.25
```

**Comment by yash-habilelabs** [comment]
@riophae Thanks for your help and code snippets. it's working for me. it's really a good package.

**Comment by djurovicigoor** [comment]
How to combine async search with this load more option? Is it possible? @riophae

**Comment by ice1245** [comment]
Man, you are a legend.  <3
