### ISSUE TITLE
Consider adding package.lock

### ISSUE THREAD

**Issue by marcelfalliere** [riophae/vue-treeselect#28]
Documentation from npm : https://docs.npmjs.com/files/package-lock.json

I wanted to contriboot to this repository. I can't because after a fresh `git clone`, `npm i` and `npm run dev` I get :

````
 ~/contriboots/vue-treeselect > npm run dev

> @riophae/vue-treeselect@0.0.6 dev /Users/ireadyouremails/contriboots/vue-treeselect
> node build/dev-server.js

/Users/ireadyouremails/contriboots/vue-treeselect/node_modules/pug-loader/index.js:155
      throw e;
      ^

Error: /Users/ireadyouremails/contriboots/vue-treeselect/docs/partials/guides.pug:37:5

true is not constant. All filters are rendered compile-time so filter options must be constants.
    at makeError (/Users/ireadyouremails/contriboots/vue-treeselect/node_modules/pug-error/index.js:32:13)
    at /Users/ireadyouremails/contriboots/vue-treeselect/node_modules/pug-filters/lib/handle-filters.js:100:15
    at Array.forEach (native)
    at getAttributes (/Users/ireadyouremails/contriboots/vue-treeselect/node_modules/pug-filters/lib/handle-filters.js:95:14)
    at walk.includeDependencies (/Users/ireadyouremails/contriboots/vue-treeselect/node_modules/pug-filters/lib/handle-filters.js:17:19)
````

**Comment by marcelfalliere** [comment]
Actually removing the "`^`" in `package.json` for the "pug" dependencies (ie fixing the rc4) fixes the `npm run dev`.

I'll push it with the PR I'm working on.

**Comment by riophae** [comment]
Yeah, `pug` indeed should be upgraded. Thanks for your contributing!

**Comment by marcelfalliere** [comment]
Thanks to you for making this awesome component.

I want to add two feature :
- always open : the selection pane is always opened and the arrow is not
present
- disable a selectable node : adding a boolean _disabled on nodes

What do you think ?

**Comment by riophae** [comment]
- always open: yeah, that's great!
- disable a selectable node: this feature was planed in the very start but still not finished yet. 

Both features I think are good.

**Comment by marcelfalliere** [comment]
I need help. `npm run dev` throws an error and I can't find the problem.
Pug seems to be the cause. I'll try to upgrade it.

To reproduce : can you try to clone the repo ?

Anyway, I'll update when I get internet back on my computer.

**Comment by marcelfalliere** [comment]
Or a more precise question for you : what is your version of pug in your
node_modules ? You can check in the package json I guess.

**Comment by riophae** [comment]
The version I am using is 2.0.0-rc.4.
Did you mean clone your fork? Seems you haven't forked...

**Comment by dabernathy89** [comment]
Hey, just wanted to jump in here. I am also unable to get `npm run dev` working on a fresh copy of the dev branch, same error message as above. Doesn't seem to change no matter what version of pug I install.
