### ISSUE TITLE
The codepen linked in the readme is broken: Refused to apply style from 'https://unpkg.com/@riophae/vue-treeselect@0.3.0/dist/vue-treeselect.min.js' because its MIME type ('application/javascript') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by dflock** [riophae/vue-treeselect#290]
The you visit the codepen linked in the readme (https://codepen.io/riophae/pen/MExgzP) it doesn't load properly and you get this:

![image](https://user-images.githubusercontent.com/47756/65201965-dd787f80-da3e-11e9-9e82-fdb16e2de49f.png)

In Chrome this error is in the console:

> Refused to apply style from 'https://unpkg.com/@riophae/vue-treeselect@0.3.0/dist/vue-treeselect.min.js' because its MIME type ('application/javascript') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by riophae** [comment]
Thanks for your feedback! It should have been fixed now.
