### ISSUE TITLE
[Delayed Loading] 'load-options' is not support async await?

### ISSUE THREAD

**Issue by lively-qcy** [riophae/vue-treeselect#291]
When I use Async Function,the `children data` is not appended
```
 async loadTreeSelectMenu({ action, parentNode, callback }) {
       let data = await getChildren(parentNode.id);  //Api：Async Request
       parentNode.getChildren = data;
       callback();      
 },
```
This way can load...
```
loadTreeSelectMenu({ action, parentNode, callback }) {
      getChildren(parentNode.id).then(data => {
        parentNode.children = data;
        callback();
      });
}
```
`load-options` can support Asycn Function?
Thanks.

**Comment by riophae** [comment]
你好，`async/await` 是可以用的，我猜问题出在这一句了：

```js
parentNode.getChildren = data;
```

应该是：

```js
parentNode.children = data;
```

**Comment by lively-qcy** [comment]
> 你好，`async/await` 是可以用的，我猜问题出在这一句了：
> 
> ```js
> parentNode.getChildren = data;
> ```
> 
> 应该是：
> 
> ```js
> parentNode.children = data;
> ```
![image](https://user-images.githubusercontent.com/39941460/65492911-5d419680-dee4-11e9-8339-3cf7681f2093.png)

I was bit messy...
Now it's working normally with async and await.
Thanks !
