### ISSUE TITLE
vue-treeselect.js file on jsdeliver CDN is not the same version as the minified one

### ISSUE THREAD

**Issue by tristanleboss** [riophae/vue-treeselect#295]
The https://cdn.jsdelivr.net/npm/@riophae/vue-treeselect@%5E0.3.0/dist/vue-treeselect.min.js file is a standalone version of Vue Treeselect.

But the file https://cdn.jsdelivr.net/npm/@riophae/vue-treeselect@%5E0.3.0/dist/vue-treeselect.js file is a WebPack bundled one.

This is not really expected: I wanted to use the non-minified version on my development site but I am unable to do so as the WebPack version will not work standalone (Uncaught ReferenceError: module is not defined).

**Comment by riophae** [comment]
Hi, now you can use the umd build for development:  
https://cdn.jsdelivr.net/npm/@riophae/vue-treeselect@%5E0.4.0/dist/vue-treeselect.umd.js
