### ISSUE TITLE
events

### ISSUE THREAD

**Issue by bm2ilabs** [riophae/vue-treeselect#3]
Hello , first of all , what a great component , i really like the documentation . 
i am a beginner in vuejs , could you please help me in the events, i did
```javascript
vm.$on('input', (value, id) => {
  console.log(value, id)
})
```
but this didn't work , btw i added this in created

**Comment by riophae** [comment]
Hi, could you please provide more code? I didn't get the idea, e.g. which component the `vm` is representing?

Regards,
Riophae Lee
________________________________

**Comment by bm2ilabs** [comment]
Sorry i didn't make that clear enough , vm just represent this means the vuejs 
`
var vm = this 
`

**Comment by riophae** [comment]
Humm... I just assume you mean `this` representing your component. It would be like:

```html
<template>
  <div>
    <treeselect ... />
  </div>
</template>
```

```js
export default {
  created() {
    var vm = this
    vm.$on('input', (value, id) => {
      console.log(value, id)
    })
  }
}
```

By doing this actually you are listening to `input` events from your own component :) The right way is:

```html
<template>
  <div>
    <treeselect @input="onInput" ... />
  </div>
</template>
```

```js
export default {
  methods: {
    onInput(value, id) {
      console.log(value, id)
    }
  }
}
```

**Comment by bm2ilabs** [comment]
thank you, that's exactly what i am looking for , thank you for this great plugin
