### ISSUE TITLE
Feature:增加value绑定类型选择

### ISSUE THREAD

**Issue by gaoshijun1993** [riophae/vue-treeselect#32]
树形选择组件绑定的value希望可以配置为一个对象数组,每一个对象里面有个isBranch字段说明这个item是leaf还是branch

**Comment by riophae** [comment]
你好，目前 value 数组只包含 id，不提供其他字段，主要是为了让逻辑更简单（因为需要考虑双向绑定之类的）。
按理来说，在业务逻辑里应该是可以做到判断每个选项到底是 leaf 还是 branch 的吧？

**Comment by gaoshijun1993** [comment]
@riophae 我们现在的应用场景是要通过树形选择组件可见的员工列表,branch就是部门,leaf就是员工,员工跟部门在数据库中是两张表来着,所以通过id来区分有点难度...

**Comment by riophae** [comment]
嗯，是这样的，如果 value 数组里面是对象的话，那么你在给组件赋初始值（就是设定默认选中的项目）的时候，也得传对象进来才行，你觉得这样可以接受吗？

**Comment by gaoshijun1993** [comment]
@riophae 考虑了一下,如果传对象的话看起来似乎是有点麻烦,但是一般也不会是手动去设置默认选中的吧?保持传进来的数据跟得到的数据格式一样,我觉得应该是可以接受的.所以传对象跟传string实际上应该不会差很多

**Comment by riophae** [comment]
默认选中一般是在编辑之前保存的数据的时候会用到。嗯……我现在也在考虑，要不要允许传入和传出的数据格式不一致，或许是可以的……

我现在设想的是这个样子的：默认 `value` 仍然是 `id` 数组，但是可以给 vue-treeselect 传一个参数，比如 `valueAsArrayOfObjects=true` 这样，然后无论你传给 vue-treeselect 什么格式，都会返回给你对象数组，每个对象里面都会有 `id`，`label`，`isBranch`，等等等等信息（也就是 vue-treeselect 内部存储的信息）。

**Comment by gaoshijun1993** [comment]
@riophae 嗯,嗯,我觉得这样子增加一个配置参数很好☺

**Comment by gaoshijun1993** [comment]
@riophae 还有在说明文档里面,引入样式文件的方式,不建议通过
`<style src="@riophae/vue-treeselect/dist/vue-treeselect.min.css"></style>`
方式引入,最好还是
`
import "@riophae/vue-treeselect/dist/vue-treeselect.min.css"
`
因为我通过前者引入,发现在style 标签里面写的样式都无效了..

**Comment by riophae** [comment]
你好，很抱歉拖了这么久，今天刚刚发布了新版本，现在 vue-treeselect 支持 `value` 为对象了：

```vue
<template>
  <treeselect :options="options" v-model="value" value-format="object" />
</template>

<script>
  export default {
    data() {
      return {
        options: [ ... ],
        value: {
          id: 'a',
          label: 'a',
        },
      }
    },
  }
</script>

```

需要注意的是，你传给 vue-treeselect 的值和组件传回给你的值都会是对象（或者对象数组）。之前曾经考虑无论什么情况都允许 `value` 既可以是 id 也可以是对象的，但是发现实现起来过于麻烦，所以现在采用的是，你设置 `valueFormat` 的格式是什么，就需要传什么格式的 `value`。如果传对象有困难的话，直接传 `{ id: 'id' }` 这样一个简单的对象也是可以的。

**Comment by zwq8299174** [comment]
这个问题前几天刚遇到，貌似现在组件传出的值是id，传入的可以是对象，我自己修改了组件貌似你说的这种既可以是id也可以是对象的是支持了，但是懒加载子节点的时候input框里显示为空会

**Comment by zwq8299174** [comment]
我觉得可以价格自定义的参数，其实这个需求也是后端抛出来的，因为他们编辑的时候传回的可能是对象，前端新建的时候给后端的可以是单独的id，所以就造成了实际上需要同时支持id和对象这种状态

**Comment by zwq8299174** [comment]
那个bug貌似我修复了，其实还有个需求就是后端过来的树结构数据对象中的显示字段肯能是title、name、lable等等这种的，现在插件貌似定死的是lable吧，我们后端过来的是name，而且他说好多接口在用，没办法改，我就改了下插件可以外面自定义显示字段，对应的想到了id也一样，也有可能是value、val、id、key各种名称，所以可以考虑加入这种取值的自定义化功能，默认可以设置成id和lable

**Comment by zwq8299174** [comment]
用的时候忘记fork了，直接拿你的源码自己放在项目里改了一下，没想那么多一开始，看到邮件里有这个问题，进来一看貌似大家都遇到这个问题了，最近比较忙，马上出差了要，要不然我直接把修改的部分对比一下推送一下就可以了.....一开始还以为这项目没人管呢...

**Comment by riophae** [comment]
@zwq8299174 目前就是参数自定义的，你可以自己选择究竟用 id 还是对象，但是不能你传进去 id 组件传回来对象这样混着。

自定义键名这个，我尽快实现一下吧，确实不止一个人提了。像 react-select，vue-multiselect 采用的都是允许通过参数的方式来自定义键名，比如说 track-by="key"，就把 “id" 给替换成了 ”key“，label 同理。

我现在的想法是这样搞，组件接受一个名为 normalizer 的函数参数，vue-treeselect 会递归地把 options 参数中的每一个节点传给这个函数，它负责做一个转换，在这个过程中可以完成自定义键名的过程。

比如说，options 中的一个节点为：

```js
{
  key: 'id',
  name: 'label',
}
```

然后：

```vue
<template>
  <treeselect :options="options" v-model="value" :normalizer="normalizer" />
</template>

<script>
  export default {
    data() {
      return {
        options: [ ... ],
        value: null,
      }
    },
    methods: {
      normalizer(node) {
        return {
          id: node.key,
          label: node.name,
        }
      },
    },
  }
</script>
```

这样好处是，因为 vue-treeselect 支持的键名不止 id 和 label（比如 isDisabled，children 等等），因此所有源数据和 vue-treeselect 要求不一致的部分可以一并解决掉，不需要搞很多个参数。你觉得这个方案可以接受吗？

**Comment by riophae** [comment]
@zwq8299174 不好意思哈，这个项目确实维护得不够及时，这段时间身体一直状态不好，耽误了

**Comment by zwq8299174** [comment]
这种方案倒是也行，另外一种思路，你的意思是保留原来的lable和id不变，只是一个自定义函数把新的名字对应到id和lable上？这样的话树结构数据如果多会不会有问题不知道。我的实现思路是用传进来的键名去取数据对象中对应的键值
```vue
<treeselect
	:placeholder="placeholder"
	:label = "label"
	:load-root-options="getData"
   	:auto-load-root-options="true"
	@input="handleInput"
	v-model="currentValue"
	:value="currentValue"
	:multiple="multiple"
	:clearable="clearable"
	:searchable="searchable"
	:readonly="readonly"
	:open-on-focus="openOnFocus"
	:open-on-click="openOnClick"
	:clear-on-select="clearOnSelect"
    :close-on-select="closeOnSelect"
	:maxHeight="360"
	:disableBranchNodes="selectBranch"
	:load-children-options="getData">
	<label
		slot="option-label"
		slot-scope="{ node, shouldShowCount, count, labelClassName, countClassName }"
		:class="labelClassName">
			<i class="iconfont option-icon" v-if="node.treeType=='office'&&node.type=='1'">&#xe623;</i>
			<i class="iconfont option-icon" v-if="node.treeType=='office'&&node.type=='2'">&#xe680;</i>
			<i class="iconfont option-icon" v-if="node.treeType=='area'">&#xe62a;</i>
			<i class="iconfont option-icon" v-if="node.treeType=='menu'">&#xe665;</i>
			<i class="iconfont option-icon" v-if="node.treeType=='user'">&#xe680;</i>
			{{ node[label] }}
	    	<span v-if="shouldShowCount" :class="countClassName">({{ count }})</span>
	</label>
</treeselect>
```
```vue
<template slot="option-label" slot-scope="{ node, shouldShowCount, count, labelClassName, countClassName }">
  <slot name="option-label" :node="node" :should-show-count="shouldShowCount" :count="count"
    :label-class-name="labelClassName" :count-class-name="countClassName">
    <label :class="labelClassName">
      {{ node[label] }}
      <span v-if="shouldShowCount" :class="countClassName">({{ count }})</span>
    </label>
  </slot>
</template>
```
刚才看代码，突然想到一个问题，就是树结构的数据源发生变化时，组件不会自动刷新，我自己在watch处监控了一下options，然后执行了一下初始化的方法就可以了，这个貌似用的人的不少，表单中组件的依赖，点击别的组件刷新树组件的数据源。

**Comment by riophae** [comment]
@zwq8299174 嗯，把 label 传到模板里的话，确实可以正常显示，但是也有其他的问题，比如会不能正常搜索。因为搜索的时候也是要找这个 label 的。我之前提出来的方案不会有性能问题，因为每个节点加载进树的时候会做一次初始化，这个 normalizer 就是在这个初始化过程中被执行的，是一次性的，并不是每次渲染都要重新执行一遍。

关于树结构数据源发生变化组件不刷新这个问题，这个是故意设计成这个样子的，文档里也有提到。我之后研究下能不能去掉这个限制。

**Comment by riophae** [comment]
刚刚发布了一个新版本 v0.0.14，现在支持自定义键名了：https://vue-treeselect.js.org/#customize-key-names

**Comment by peizhenxing** [comment]
![error](https://user-images.githubusercontent.com/26026238/39396636-28e46106-4b24-11e8-8aab-030b75a78b12.png)
![question](https://user-images.githubusercontent.com/26026238/39396637-2935832e-4b24-11e8-868e-7894c869e2e7.png)
您好...我有个问题...不知道应该怎么解决..麻烦了哈

**Comment by zhoujin123** [comment]
@riophae 你好，首先感谢你！其次我想问下value为对象的话，回传给我的是个数组对象，那编辑回显的时候绑定值应该是怎么样的，因为初始化的时候绑定的值是一个object类型的，并且初始化绑定的值为空的时候，unKnown的问题是怎么解决了的
