### ISSUE TITLE
文字过长，导致后面的内容显示点点点

### ISSUE THREAD

**Issue by qudawei** [riophae/vue-treeselect#327]
1.期望鼠标放入可以设置title属性显示完全，救救孩子吧！
![image](https://user-images.githubusercontent.com/18113748/70371995-aebec680-1914-11ea-8b61-82a568f451b8.png)

**Comment by KevinPangjh** [comment]
<treeselect
            @open="getOptions(typeItem)"
            v-model="typeItem.meta.value"
            :multiple="true"
            :options="typeItem.meta.options">
            // 根据官方的文档加上label，slot取值option-label
           // 由于我这边给它加上这个以后，导致后面的小数点失效，所以我主动切割字符串
           // 默认显示9个字符，span-ellipsis可以忽略
            <label slot="option-label"  slot-scope="{node}" >
                   <span :title="node.label" class="span-ellipsis">
                             {{ node.label.split("").length >9 ? (node.label.split("",9).join(""))+"..." : node.label}}
                   </span>
            </label>                     
 </treeselect>

**Comment by qihb** [comment]
> 添加自定义节点（官方文档说明在：Customize Option Label）然后在上面自己加一个title就可以实现鼠标放上去提示的效果
```js
<treeselect
    :options="options"
    :load-options="loadOptions"
    placeholder="请选择"
    v-model.trim="consignorId"
  >
      <label slot="option-label" 
        slot-scope="{ node, shouldShowCount, count,countClassName, labelClassName }" 
        :class="labelClassName"
        :title="node.label" >
        {{ node.label }}
      </label>
</treeselect>
```

**Comment by wuRoyell** [comment]
能不能让文字撑起宽度，宽度自适应和el-tree一样的效果。
