### ISSUE TITLE
Make it possible to hide caret for a root level node without children

### ISSUE THREAD

**Issue by glazjoon** [riophae/vue-treeselect#347]
Me and my colleagues are using this great library with great success. However, we have been trying to find a way to hide the caret when a node on the root level has no child. Is this already possible?

Thanks for the great work!

**Comment by ciryon** [comment]
It appears if the "children" property is absent (rather than being an empty array) then the node is displayed without caret.

**Comment by mr-Sepi0l** [comment]
I have the same problem. Last children have caret and when I click them it just tells me the is no sub folder. 
I use the `:disable-branch-nodes="true"` so I can't select anything in my select. 

I tried to remove children node and to  set it as an empty array, as null, none of the solution worked...

**Comment by iarkaroy** [comment]
It looks like the caret would not be displayed if the "children" property is `undefined`.

**Comment by glazjoon** [comment]
> It appears if the "children" property is absent (rather than being an empty array) then the node is displayed without caret.

This is the solution.
