### ISSUE TITLE
作者你好，options是ajax获取的，选项无法显示，该怎么做？

### ISSUE THREAD

**Issue by lizongwen** [riophae/vue-treeselect#35]
作者你好，options是ajax获取的，选项无法显示，该怎么做？

**Comment by riophae** [comment]
你好，AJAX 获取选项之后是不是修改了 options 数组？如果是这样的，vue-treeselect 会没有反应的。你应该用 loadChildrenOptions/loadRootOptions 参数。
可以参考这部分文档：https://riophae.github.io/vue-treeselect/#delayed-loading

**Comment by lizongwen** [comment]
按照你的提示，已经解决了问题，感谢！
