### ISSUE TITLE
issue: Changing options via a refresh method

### ISSUE THREAD

**Issue by jeden1974** [riophae/vue-treeselect#36]
Hi,
Is there a chance of having a refresh method added to the control so that an external component can tell the tree to reload it's options?
Many thanks
Jon

**Comment by jeden1974** [comment]
I managed to get this working using a ref on the component and then in the watcher for the options I added 
    options: function (data) {
      this.$refs.treeselect.initialize(data)
    }
This seems to work, whether it is the best approach that's another question...

**Comment by riophae** [comment]
Hi @jeden1974! A new version just released, please check out: https://github.com/riophae/vue-treeselect/issues/63#issuecomment-382154000
