### ISSUE TITLE
issue: disabling specific nodes

### ISSUE THREAD

**Issue by jeden1974** [riophae/vue-treeselect#37]
Hi,
With some of my controls if you are editing an item in a self referencing tree then I use a tree for selecting the parent.  I would like to be able to disable the selection of a child element.  So it would be nice if the control allowed the options node array to have a disabled or blocked value that would prevent the selection of that item - but allow any that had the value set to false.

Hopefully thats understandable :)

Many thanks
Jon

**Comment by riophae** [comment]
Hi, this feature has just landed in v0.0.8. Check out the docs here: https://riophae.github.io/vue-treeselect/#disable-item-selection
