### ISSUE TITLE
Delayed loading not work

### ISSUE THREAD

**Issue by MeFelixWang** [riophae/vue-treeselect#393]
The component always show "No Sub-options" when using loadOptions, here is the code:

``` 
 async loadOptions({action, parentNode, callback}) {
        if (action === LOAD_CHILDREN_OPTIONS) {
          const {name} = parentNode;
          if (name) {
            const {data} = await getSubCategory({name});
            parentNode.children = data;
            callback();
          } else {
            parentNode.children = [];
          }
        }
      }
 ```
How can I solve this problem?

**Comment by ccharz** [comment]
Try adding your children to the callback: `callback(null, data);`

**Comment by MeFelixWang** [comment]
Thanks for reply, but still not work, any other suggestions? @ccharz

**Comment by MeFelixWang** [comment]
When the async data returns, I can see them in parentNode after set "parentNode.children=data",  the component seems not to be rerendered. @ccharz

**Comment by scbing** [comment]
@MeFelixWang  The same problem, how did you solve it

**Comment by d3249** [comment]
I have the same issue, any hints on how to solve?
