### ISSUE TITLE
vue-treeselect刷新界面后显示样式有问题

### ISSUE THREAD

**Issue by chenprincess** [riophae/vue-treeselect#406]
我在一个项目中的多个位置使用了本组件，但在某些地方显示样式存在问题，当我点击正常的其他位置的组件后再重新点击出现问题的组件便可以正常显示，当时当我继续刷新页面后显示样式还是会出现问题，显示的问题是展开的小三角形变成很大的图标，经过查看可以发现vue-treeselect__control-arrow-container等类的样式失效，但较其他并未进行特殊操作，望回复，谢谢。以下为显示照片及使用的代码：
![1603868952(1)](https://user-images.githubusercontent.com/37969075/97412945-2dfa2600-193d-11eb-8275-15e3f51e1f8b.jpg)

`<tree-select v-model="saveForm.xzqhbianhao" :multiple="false"
                       placeholder="请选择行政区划"
                       :options="xzqhData"
                       :normalizer="normalizer" @select="selectDepart"></tree-select>`

**Comment by lk5103613** [comment]
将样式引入放到main.js中
import 'normalize.css/normalize.css'

**Comment by chenprincess** [comment]
> 将样式♡放到main.js中
> 导入'normalize.css / normalize.css'

谢谢，问题已经解决。

**Comment by duan210503** [comment]
我遇到相同问题，请问除了将样式引入main.js中，还有其他注意的设置吗，我引入样式后，还是不起作用

**Comment by chenprincess** [comment]
> 我遇到相同问题，请问除了将样式引入main.js中，还有其他注意的设置吗，我引入样式后，还是不起作用

不光要在main.js中引入样式，还需要在使用的文件中单独引入样式，import '@riophae/vue-treeselect/dist/vue-treeselect.css'。

**Comment by duan210503** [comment]
解决了，感谢。
