### ISSUE TITLE
Treeselect in Bootstrap (3) navbar.

### ISSUE THREAD

**Issue by ArtisanTinkerer** [riophae/vue-treeselect#41]
Hi,

I am trying to drop your control into a Bootstrap navbar. (A bit like the search box on Github).

It would be fantastic if it was as easy as this:

[https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_navbar_form&stacked=h](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_navbar_form&stacked=h)

Is this something you would be interested in doing? I imagine that other people would also desire this.

Thanks,

Mick

**Comment by ArtisanTinkerer** [comment]
![nearly](https://user-images.githubusercontent.com/13234475/37709137-1bbefec8-2d01-11e8-91f6-ad219df97d09.png)

Hi, I have done this, I just need to move the icons now. Any tips on how to do this?

Thanks,

Mick

**Comment by ArtisanTinkerer** [comment]
I have this now, I needed a table-row in there. Thanks.

**Comment by riophae** [comment]
Glad to see your problem got solved! I'm going to close this thread now.
