### ISSUE TITLE
why "unknown" show?

### ISSUE THREAD

**Issue by FanNanTx** [riophae/vue-treeselect#43]
i use souce options of the doc ,but treeselect show "unknown"?
![image](https://user-images.githubusercontent.com/31879078/37821275-21ba8590-2ebe-11e8-89e4-6aa21cc20d72.png)
![image](https://user-images.githubusercontent.com/31879078/37821311-358538f4-2ebe-11e8-84e2-43e1804f3884.png)
thank you!

**Comment by ZeroJsus** [comment]
在v0.0.16 上问题依旧

**Comment by riophae** [comment]
@FanNanTx @ZeroJsus 抱歉，可能是我理解错了！
是这个样子的，可能你用到了延迟加载，如果预选中了选项，而这个选项没有加载进来的话，那么 vue-treeselect 只知道它的 id 而不知道 label，所以只能显示为“unknown”。具体解决方案请参考：https://github.com/riophae/vue-treeselect/issues/4

**Comment by xingxiaobei** [comment]
初始值为空，框中就显示（unknown）？

**Comment by jason12138** [comment]
> @FanNanTx @ZeroJsus 抱歉，之前是我理解错了！
> 是这个样子的，可能你用到了延迟加载，如果预选中了选项，而这个选项没有加载进来的话，那么 vue-treeselect 只知道它的 id 而不知道 label，所以只能显示为“unknown”。具体解决方案请参考：#4

您好，我想问一下，为什么我将值回传到组件上时只自动勾选了父级，子级显示unknown？
