### ISSUE TITLE
option无法展示label值，展示空白内容?而且选项箭头位置不居左?

### ISSUE THREAD

**Issue by FanNanTx** [riophae/vue-treeselect#44]
![image](https://user-images.githubusercontent.com/31879078/37862757-473d5412-2f8d-11e8-8889-b6ce2a4e0148.png)
![image](https://user-images.githubusercontent.com/31879078/37862760-5dff110e-2f8d-11e8-91ce-9bc001ac6135.png)

用的是文档中的options source，但是展示结果如上图 无法使用
Thank You!

**Comment by riophae** [comment]
你好，看上去像是样式问题？可以提供更多信息吗，比如搭配了什么前端框架？

**Comment by FanNanTx** [comment]
你好，前端框架用的是bootstrap,是放在模态框里使用的，我检查下了页面元素，发现我的页面上
 treeselect_label-wrapper内 没有label的内容，而官网上的例子则有
![image](https://user-images.githubusercontent.com/31879078/37882629-86f43918-30d7-11e8-8dbb-8bc556802d25.png)

**Comment by FanNanTx** [comment]
![image](https://user-images.githubusercontent.com/31879078/37882651-c2f3bc22-30d7-11e8-96a9-a4b57483bbf4.png)
这是你官网上的则有

**Comment by riophae** [comment]
嗯，这样看来不是样式问题了，可以把你调用 vue-treeselect 这一部分的代码贴出来看看吗？console 里面有没有报错？Vue 是不是最新版本？

**Comment by FanNanTx** [comment]
你好，vue版本是 2.2.1,控制台也没有报错
treeselect我目前是按官网最简单的方式配的,
![image](https://user-images.githubusercontent.com/31879078/37883151-4abf268e-30db-11e8-9354-16a16b1b1e35.png)

![image](https://user-images.githubusercontent.com/31879078/37883130-2ed6db7e-30db-11e8-859e-041a689f29db.png)

![image](https://user-images.githubusercontent.com/31879078/37883206-aac8bfea-30db-11e8-888e-b676efa808f3.png)

**Comment by riophae** [comment]
嗯，在这里建议你先试一下升级 Vue 到新版看看，原因是，这个 label 的地方用到了 scoped slots，旧版本可能支持得不好

**Comment by FanNanTx** [comment]
你好 刚升级vue至2.5.16 试了还是不行 label仍然无法展示
![image](https://user-images.githubusercontent.com/31879078/37883900-ceb854c0-30df-11e8-91e0-bd9126ff1c43.png)

**Comment by riophae** [comment]
@FanNanTx 我刚刚试了一下，我也是把文档里那段代码直接复制了过来，发现是正常的……还有什么别的信息可以提供吗？

**Comment by FanNanTx** [comment]
我在新搭建的vue空项目里使用是正常的，但是在我的项目中我实在找不到导致出现这种情况的原因

**Comment by riophae** [comment]
@FanNanTx 这样说的话，似乎还是和你这个项目配置有关系？从目前提供的这些信息，我也实在没有啥别的建议了
