### ISSUE TITLE
option 不支持扩展属性吗

### ISSUE THREAD

**Issue by somnusnrlq** [riophae/vue-treeselect#45]
我的数据格式
[{id:'11',label:'222',children:[],num:''}]  这样的数据格式就会有问题

**Comment by riophae** [comment]
可以有额外的属性的，有什么报错吗？

**Comment by somnusnrlq** [comment]
下拉框老提示：No options available

 `<template>
  <treeselect  :options="tableData" :value="value" >

  </treeselect>
</template>

<script>
import Treeselect from '@riophae/vue-treeselect'

export default {
  components: { Treeselect },
  props: {
    treeDataFZDW: {
      type: Array,
      default: function () {
        return []
      }
    }
  },
  mounted() {
    this.tableData = this.treeDataFZDW
  },
  watch: {
    treeDataFZDW(data) {
      console.info(data)
      this.tableData = data
    }
  },
  data() {
    return {
      tableData: [],
      value: null
    }
  }

}
</script>

<style src="@riophae/vue-treeselect/dist/vue-treeselect.min.css"></style>`

这是我的组件代码

**Comment by somnusnrlq** [comment]
下拉框老提示：No options available
   

![qq 20180327134403](https://user-images.githubusercontent.com/10290501/37948946-12f0176e-31c5-11e8-8d5b-609e10a12ed4.jpg)

**Comment by riophae** [comment]
明白了，vue-treeselect 是这个样子的，它只认你第一次传进去的数据，比如你这里用的是 tableData，你改它的值 vue-treeselect 是不会反应的。你应该直接把 treeDataFZDW 传给 options 这个参数，mounted 和 watch 都不需要。
