### ISSUE TITLE
Reset components in LOAD_ROOT_OPTIONS

### ISSUE THREAD

**Issue by fbiagetti** [riophae/vue-treeselect#463]
Hi Friends, how are u?

I have one bug or problem i dont know.
My problem is when i use LOAD_ROOT_OPTIONS and i change the options (because i have conditions depend the product) the options dont reset. Any have idea if i have one code to reset values or component ?

**Comment by TitanFighter** [comment]
Show your code, for example here https://codesandbox.io/
