### ISSUE TITLE
options are not working with Vuex

### ISSUE THREAD

**Issue by marekkaczkowski** [riophae/vue-treeselect#47]
Hey Fangzhou,

Struggling with `vue-treeselect` to make it working with options from Vuex store that are fetched in created meth. Looks like treeselect is not reactive:
- Tried regular Vuex way
- tried to get data with Promise than resole it in component where `vue-treeselect` is used

Any ideas?

**Comment by riophae** [comment]
Hi, I'm sorry, but currently vue-treeselect only has a very basic support for working with Vuex. vue-treeselect needs to maintain options internally and will not react to changes of your array of options after the data initialization. If you are using Vuex, it's even worse. Only the `value` is well supported, not `options`. I'll work more on that later.

There is a little space you can work around now:

```vue
<template>
  <treeselect
    :load-root-options="loadRootOptions"
    :value="value"
    @input="updateValue"
    />
</template>

<script>
  import Vue from 'vue'
  import Vuex, { mapState, mapMutations } from 'vuex'

  Vue.use(Vuex)

  const Deferred = () => {
    let ok, ng
    const promise = new Promise((resolve, reject) => {
      ok = resolve
      ng = reject
    })
    promise.resolve = ok
    promise.reject = nj
    return promise
  }

  const optionsPromise = Deferred()

  const store = new Vuex.Store({
    state: {
      value: 'a',
      options: [],
    },
    mutations: {
      updateValue(state, value) {
        state.value = value
      },
      updateOptions(state, options) {
        state.options = options
        optionsPromise.resolve(options)
      },
    },
    actions: {
      loadOptions({ commit }) {
        $.get('/api', data => {
          const { options } = data
          commit('updateOptions', options)
        })
      },
    },
  })

  export default {
    computed: {
      ...mapState([ 'value' ]),
    },
    methods: {
      ...mapMutations([ 'updateValue' ]),
      loadRootOptions(callback) {
        optionsPromise.then(options => {
          callback(null, options)
        }, error => {
          callback(error)
        })
      },
    },
  }
</script>
```

But this is very limited. You cannot load more options after the first AJAX call. I hope this could be helpful, but it's very likely to be useless.

I'll pay more effort on letting `options` prop reactive.

**Comment by marekkaczkowski** [comment]
Thanks, I'll play with it :)
