### ISSUE TITLE
Update currently selected nodes as ajax data comes in

### ISSUE THREAD

**Issue by Alig96** [riophae/vue-treeselect#49]
Currently, if you set the source of the tree before the node information has been received (via ajax), then the id of the node is shown. 
`1 (unknown)`
This is expected since the label data isn't there yet. However, when you open the children of the node, I can see that its pre-selected in the tree area, which is great, but it should also update in the "selected/search area" as soon as you open the parent node and data is loaded.

The problem corrects itself if you un-select the node and re-select the node, which fixes all nodes it has data for.

Hopefully this should be as easy as just calling an update method when we expand the parent.

**Comment by riophae** [comment]
Hey Alig, are you using an old version? This bug should have already been fixed: https://github.com/riophae/vue-treeselect/releases/tag/v0.0.12

**Comment by Alig96** [comment]
Can confirm I'm on latest (v0.0.15)

**Comment by riophae** [comment]
Thanks for your feedback. Have reproduced the bug. Currently working on it.

**Comment by Alig96** [comment]
Works perfectly! 👏🎉

Thank you!
