### ISSUE TITLE
Excuse me, why I had use $.ajax to get options, but `vue-treeselect` not work.

### ISSUE THREAD

**Issue by zgj233** [riophae/vue-treeselect#5]
I had use $.ajax to get some result, and bind with ``` :option```.
But ```vue-treeselect``` show me "no options avaliable".
my result's format fits your rules.

**Comment by riophae** [comment]
似乎是直接修改了你绑定的那个 options 数组？vue-treeselect 由于实现上的原因，不能响应 options 数组的变化，所以如果需要动态加载选项的话，请参考一下文档这个部分：https://riophae.github.io/vue-treeselect/#delayed-loading

**Comment by zgj233** [comment]
谢谢啦，朋友。不过你怎么知道我是中国的

**Comment by riophae** [comment]
@zgj233 点进你主页就知道了~

**Comment by zgj233** [comment]
多谢提醒，我现在就去把它改了嘿嘿

**Comment by zgj233** [comment]
@riophae 朋友请问下如何将已选择了的项，主动赋值给 vue-treeselect。绑定的v-model , 并且让它正确显示出来呢？ 我看官方文档里面写了vuex 的方法，但是写得不是很详细。谢谢

**Comment by riophae** [comment]
指的是在初始的时候预先选中吗？

**Comment by zgj233** [comment]
嗯嗯，是的

**Comment by riophae** [comment]
在你 Vuex Store 的 state 里预先给 value 设置值就好了。你看一下文档 Vuex Support 这一节的例子，初始的时候 state 里 `value` 是 `"a"`，指的就是预先选中 id 为 `"a"` 的这一项（单选模式）。如果多选模式，`value` 应该是数组。

**Comment by zgj233** [comment]
必须用vuex是吧，好的谢谢啦

**Comment by riophae** [comment]
额，不是的，不是必须用 Vuex……我看你意思以为你用的是 Vuex 呢……
总之就是，`v-model` 里面指定的那一个，比如是 `value`，那么你可以通过在 `data: {}` 里面给 `value` 设定初始值来预先选中特定选项

**Comment by zgj233** [comment]
嗯我是用ajax 从服务器拿到用户已经选择了的标签， 想把这些标签赋值给 vue-treeselect. 
我```vue-treeselect```上面绑定了一个v-model = lab
但是如果我把得到的数组arr，直接赋值 ```this.lab = arr``` vue-treeselect 并不能正确呈现，而是已
```[object, Object](unknown)``` 的样子 在输入框中呈现出来。
ps： 我的arr 数据结构和v-model 的数据结构也是一样的。arr 是 ```[{id:1,label:'新闻'},{id:2,label:'足球'}]```
这样的形式。

**Comment by riophae** [comment]
嗯，问题就在这个地方了，应该是类似这样：`this.lab = [ 1, 2 ]` 得是一个由 id 构成的数组才行。

**Comment by zgj233** [comment]
@riophae 谢谢你啊朋友，帮了我这么久。
再请教一个问题，```vue-treeselect ``` 能不能自动异步加载`options`， 我现在使用 ``:load-root-options`` 必须要手动点击一下输入框，它才调用。蛋疼

**Comment by riophae** [comment]
对，确实有这个问题

**Comment by zgj233** [comment]
而且 `v-model`也是要在 `options` 有值的情况下才能正确显示。如果用户的`options` 是异步调用的， 就需要再在`call(null,res)`后写一个`watch`了。 :+1:

**Comment by riophae** [comment]
这个问题，我之前测试的时候遇到了，但是没有想到妥善的解决办法……有没有什么建议？

因为，如果一个选项是异步加载的，那么在这个选项加载进来之前，vue-treeselect 是不知道它的 label 的，所以不能正常显示。（现在也存在一个问题是，即便选项加载了进来，也还是不能正常显示它的 label，得用户再选中或取消选中一个选项才能看到变化）

比如说，a 代表一级选项，aa 代表二级选项，二级选项是异步加载进来的。如果预先选中了 aa，初始的时候还没加载二级选项，也就不知道 aa 的 label 是什么，必须等到用户展开了二级选项。有没有可能主动去加载 aa 呢？

假如有这样一个后端接口，可以一次性查询 aa 的所有祖先节点、兄弟节点（或许还可以一并查询后代节点），似乎就好了……

**Comment by riophae** [comment]
@zgj233 请看一下这条评论 https://github.com/riophae/vue-treeselect/issues/4#issuecomment-341943297
