### ISSUE TITLE
Documentation misleading

### ISSUE THREAD

**Issue by ThomasKlessen** [riophae/vue-treeselect#50]
In the documentation @ https://vue-treeselect.js.org/#node the explanation for `children` says:
_Declares a branch node. Set to empty array for no children options. Set to null for delayed loading._

But in my tests it seems as if you have to set children to `undefined`. If children is an empty array you can expand the item and see an error message saying: "No children options"

**Comment by riophae** [comment]
Hi Thomas! Can you provide some suggestions on improving the doc? Absolutely welcome!

I think it's necessary to make things clear here: `children=[]` means no children options and will not load more. `children=undefined` or `children=null` means no children **at the moment the component is mounted**, but will load more as long as you expand it.

**Comment by ThomasKlessen** [comment]
I will work on this and create a PR if i'm done.
