### ISSUE TITLE
Troubles with custom value change

### ISSUE THREAD

**Issue by GieMik8** [riophae/vue-treeselect#51]
Hi, first of all - cool plugin, good job. Anyway got some troubles using it: tried to investigate where is a bug. Let me explain: the problem starts when I change the value manually from outside your plugin, I have connected your plugin with vuex store by using props ":value" (v-model is not used here). On change event I commit and change the value in store. This way I make sure that it is connected to store (sort of two way binding). Everything works as expected until I change "valueFormat" to "object", I keep whole object not only ID, also, there are several levels in a tree.  When I change the value from outside, I'm making sure that the value passed to vue-treeselect plugin has changed as well, but somehow/somewhere in components inside your plugin doesn't keep up with this change. I guess it isn't capable to detecting changes of reference type objects. I tried copying it totally using method: JSON.parse(JSON.stringify(value)) - doesn't help it.

Made some pics:
[https://ibb.co/bWyfXH](https://ibb.co/bWyfXH) (Example before)
[https://ibb.co/cXqSCH](https://ibb.co/cXqSCH) (Example after) - Here: after changing the value visually there are no changes in component

Would be helpful if you could help solving this issue, everything else is working perfectly..:

**Comment by riophae** [comment]
Hi! As the screenshots you provided, I have seen your before/after values are:

Before:
```js
[ {
  id: 1,
  label: 'Konsultacija',
  children: [ {
    id: 2,
    label: 'Konsultacija child 1',
  }, {
    id: 3,
    label: 'Konsultacija child 2',
  }, {
    id: 4,
    label: 'Konsultacija child 3',
  } ],
} ]
```

After:
```js
[ {
  id: 1,
  label: 'Konsultacija',
  children: [ {
    id: 2,
    label: 'Konsultacija child 1',
  }, {
    id: 3,
    label: 'Konsultacija child 2',
  } ],
} ]
```

Seems you were attempting to deselect `Konsultacija child 3` by removing it from the `children` array. Actually, this is not the way what vue-treeselect designed to be used (maybe I should add more detail on this in the doc). You should pass only the children as value:

```js
[ {
  id: 2,
  label: 'Konsultacija child 1',
}, {
  id: 3,
  label: 'Konsultacija child 2',
} ],
```

Remember, when `valueFormat="id"`, you need to pass `[ 2, 3 ]`, right?

Hope this could be helpful! :D

**Comment by GieMik8** [comment]
Heya, glad you reviewed this - respect 👍 

Mmm, as I understood you are saying, that I should reformat the value structure I'm passing.. mmm. Just extract the values to become first level in array. :|

> Remember, when valueFormat="id", you need to pass [ 2, 3 ], right?

And I set valueFormat to "object", so I'm passing full objects instead of id's. Will it work if I:

`[ {
  id: 1,
  label: 'Konsultacija',
  children: [ {
    id: 2,
    label: 'Konsultacija child 1',
  }, {
    id: 3,
    label: 'Konsultacija child 2',
  } ],
} ]`

change value like this:

`[ {
    id: 2,
    label: 'Konsultacija child 1',
  }, {
    id: 3,
    label: 'Konsultacija child 2',
  } ]`

Anyway will try to sort it out. Will inform you how it end up. Thanks again @riophae :)

**Comment by GieMik8** [comment]
Heya, forgot to inform about my trouble here - it works well now. Thanks :)

**Comment by riophae** [comment]
@GieMik8 Happy to hear that! I am closing this thread.
