### ISSUE TITLE
Feature Request: search/query-string should search in all parents

### ISSUE THREAD

**Issue by ThomasKlessen** [riophae/vue-treeselect#52]
What i want to achieve is the ability to search with parents included.

Imagine this list:

- A
   - 1
   - 2
   - 3
- B
   - 1
   - 2
   - 3

If i search for `1` i got 2 matches.
What i want is the ability to search for `A 1` and get only 1 result.

I already implemented this feature in my fork and could provide a PR after i updated the docu and the tests.

This is my name for that new prop:
```js
{
        name: 'searchNested',
        type: 'Boolean',
        defaultValue: v('false'),
        description: `Set true if the searchquery should search in all parent nodes to. For example Children->Mike will match "ch ke"`,
      }
```

Is this something you want?
Or do you need more info on this?

I would be glad to help you with this amazing useful component!

**Comment by riophae** [comment]
Hi Thomas! Thanks for your contribution. I think this feature is pretty useful! Fell free to create a PR.
