### ISSUE TITLE
多次的修改options的值

### ISSUE THREAD

**Issue by lovebslq** [riophae/vue-treeselect#58]
你好
请问有没有办法重新修改options选项的值，我要多次的去修改，我应该怎么去触发呢

**Comment by riophae** [comment]
你好，很抱歉暂时是不支持的，这个功能接下来就会开发的

**Comment by lovebslq** [comment]
你好
      那我现在有什么好的办法可以解决这个问题呢，您给点建议吧， 还有，你们这个新功能大概多久上线呢
