### ISSUE TITLE
Checkmark off with Bootstrap

### ISSUE THREAD

**Issue by paulheijman** [riophae/vue-treeselect#6]
First of all thank you for a very nice component!
I'm using it in a Laravel application and everything works nicely, but the checkmark is off by a few pixels (see screenshot).
<img width="193" alt="screen shot 2017-10-31 at 16 15 20" src="https://user-images.githubusercontent.com/16876395/32231924-242231de-be57-11e7-9b8e-e1351345f5a3.png">

The issue is with the Bootstrap CSS. See the following pen: https://codepen.io/paulheijman/pen/LOVzjP

Can you please have a look at it?

Also, what is the best way to override the default CSS used by treeselect?

Thanks in advance!

**Comment by riophae** [comment]
Thanks for your feedback! I saw the same on Windows.

**Comment by paulheijman** [comment]
It's got something todo with the following declaration in bootstrap.css:
```css
*:after { 
  -webkit-box-sizing: border-box; 
     -moz-box-sizing: border-box; 
          box-sizing: border-box; 
} 
```
Fixed it by changing style.css:
```
diff --git a/src/style.less b/src/style.less
index e4ca506..cd20824 100644
--- a/src/style.less
+++ b/src/style.less
@@ -714,6 +714,7 @@
     opacity: 0;
     display: table;
     transition: @treeselect-transition-duration all ease (@treeselect-transition-duration / 3);
+    box-sizing: content-box;
   }

   // minus mark
```

**Comment by riophae** [comment]
Yeah, exactly.
![screenshot](https://user-images.githubusercontent.com/1289884/32270988-f532e210-bf32-11e7-8cd3-cf47370afa05.png)

**Comment by riophae** [comment]
As for style overriding, unfortunately it's not implemented yet. At present the only way to modify the style is add your own CSS after `vue-treeselect.min.css`. 
The initial planning is expose source LESS files and then you can modify the variable values. However I have not made that clear. Do you have any suggestions?
