### ISSUE TITLE
two treeselect, one depends on the value of the other doesn't work

### ISSUE THREAD

**Issue by euricovidal** [riophae/vue-treeselect#60]
It's possible use two treeselect, one depends on the value of the other, like field to select `country -> state -> city`

I made an example on jsfiddle https://jsfiddle.net/eywraw8t/36045

thank you for any help 😄

**Comment by riophae** [comment]
Hi, good idea! However, currently vue-treeselect doesn't support dynamically setting options, you can only dynamically load children options using related props. But I am paying efforts on changing this. So, stay tuned!

**Comment by riophae** [comment]
Hi @euricovidal! A new version just released, please check out: https://github.com/riophae/vue-treeselect/issues/63#issuecomment-382154000

**Comment by euricovidal** [comment]
🎉 😮 awesome! thx
