### ISSUE TITLE
Merge thread of updating options and re-render

### ISSUE THREAD

**Issue by chinesedfan** [riophae/vue-treeselect#63]
Several issues(#16, #17, #18, #36, #58, #60) have request this feature. Let's track in one place.

One workaround is to use `this.$refs.treeSelect.initialize(newOptions)`, but the expanded/collapsed status will be reset. Hope @riophae can solve it as soon as possible. If you already have some ideas but are too busy to implement, please share with me and maybe I can help.

**Comment by riophae** [comment]
你好，非常感谢！
实际上我现在已经在本地实现了这个功能（没把代码提交上来），但是还缺少单元测试，文档方面估计也会需要不少改动。我会尽快完成的。

**Comment by riophae** [comment]
刚刚发布了新版本 v0.0.21，初步实现了这个功能。现在允许传递新的 `options` 参数给 vue-treeselect，也可以在旧的 `options` 数组上做修改（比如修改 `label` 等）。但是目前只是最基本的实现，还有不少改进的空间，比如对异步搜索的支持、调整延迟加载机制（打算废弃掉已有的 `loadRootOptions` 和 `loadChildrenOptions` 参数），等等。这个版本应该可以满足最基本的使用。

Just release a new version v0.0.21 with this feature included. Now it's possible to pass a new `options` prop to vue-treeselect, and also directly modify old `options` array (e.g., modify `label` of a `node` object). However, currently there is only the very basic implementation with much room for improvement, e.g., support for async searching, new delayed loading mechanism (planning to deprecate `loadRootOptions` & `loadChildrenOptions` props), etc. But this version should be enough for basic usage.

**Comment by riophae** [comment]
Hi! Async searching is finally landed in v0.0.31. Check out: https://vue-treeselect.js.org/#async-searching
