### ISSUE TITLE
Customize Key Names 中的normalizer默认配置选项？

### ISSUE THREAD

**Issue by gaoshijun1993** [riophae/vue-treeselect#66]
使用过程中发现我用了normalizer来自定义Customize Key Names的时候，必须要把id，label，children，isBranch给全部写全，因为貌似如果不写的话就不会生效，是否可以增加默认配置？

**Comment by gaoshijun1993** [comment]
update

**Comment by riophae** [comment]
好建议！接下来会改的。

**Comment by riophae** [comment]
现在是这个样子的，比如说，如果你的原始数据里面只有 `key` 需要调整为 `id`，而其他的比如 `label` `children` 等等都不需要做调整的话，那么你只需要返回 `key` 这一个就好了：

```js
function normalizer(node) {
  return {
    id: node.key,
    // label, children 等可以省略
  }
}
```
