### ISSUE TITLE
[Document Request]: more introduction about autocomplete

### ISSUE THREAD

**Issue by yqnetwork** [riophae/vue-treeselect#68]
自动补全应该是treeselect重要的一个额外功能。不一定要是树形结构，也可以用作查询项。但是文档没有单独讲到。
我在用treeselect做autocomplete input的过程中，就遇到treeselect弹出面板的弹出项前面默认留了一个箭头的位置。实际上，autocomplete大多数情况只是一个数组，并不会有二级菜单，所以那个箭头就很难看。
所以，希望在文档中补充autocomplete案例，重视autocomplete功能。

**Comment by riophae** [comment]
你好，我刚才想了下，准确地说 vue-treeselect 现有的功能不能算得上是 autocomplete，毕竟不支持方向键在选项间切换选择然后自动补全。我应该在介绍去掉这一条。

关于箭头的问题，我也是觉得比较丑。刚刚想到了去掉的办法，接下来会做这一块的。但是只会处理一级菜单。只要存在二级选项，这个留空就会保留。

**Comment by yqnetwork** [comment]
我保留autocomplete的意见。目前treeselect的工作量比较忙，autocomplete应该是照顾不上。但我觉得treeselect可以把输入功能概括进来。

箭头的问题，只处理第一级或者不处理都是妥当的。我当时是考虑作为autocomplete这种只有第一级的时候不需要箭头。

**Comment by riophae** [comment]
刚刚发布了 v0.0.28，终于支持用键盘操作了，可以试一下
