### ISSUE TITLE
Can't get the id info.

### ISSUE THREAD

**Issue by szagnesc** [riophae/vue-treeselect#69]
i want to know what id does user selected, but when i use 'select' event, i can't get the id info. it show "null", would you help me to solve it ? thanks.

**Comment by riophae** [comment]
I can't reproduce. Can you paste your code here?

**Comment by szagnesc** [comment]
<treeselect name="noticeTree" :multiple="multiple" :clearable="clearable" :searchable="searchable" :disabled="disabled" :open-on-click="openOnClick" :open-on-focus="openOnFocus" :limit="50" :max-height="400" :options="userList" noChildrenText='' :showCount="true" placeholder="请选择" @select="getSelectedUser" />

 getSelectedUser(node,id){
            console.log(node,id)
        }

**Comment by szagnesc** [comment]
attached my code, i can't get the selected id.  besides, how can i set all options are expanded ? i tried to use "isDefaultExpanded", but its' not workable. check my code as below.

<treeselect :options="planItems" placeholder="请选择" :key="treeKey" noChildrenText='' :showCount="true" @select="getSelectedUser" :is-default-expanded="expand"></treeselect>

data(){
return {
expand:true}
}

**Comment by riophae** [comment]
你好！`id` 实际上并不是选项的 `id`，而是你传给 vue-treeselect 的 `id` 参数。如果你需要知道选项节点的 `id` 的话，应该从 `node` 里面去取。

需要默认展开所有选项的话，可以用：`<treeselect :default-expanded-level="Infinity" />`

**Comment by szagnesc** [comment]
谢谢回复。很奇怪的是仍然无法展开所有选项。请看图。
![image](https://user-images.githubusercontent.com/29177416/39224815-ac7db89c-487b-11e8-8c7b-7509956ddcfb.png)
<treeselect :options="planItems" placeholder="请选择" :key="treeKey" noChildrenText='' :showCount="true" @select="getSelectedUser" :default-expanded-level="Infinity"></treeselect>

**Comment by riophae** [comment]
不好意思！是我写错了，参数名应该是 default-expand-level
________________________________

**Comment by szagnesc** [comment]
哈哈，可以了，谢谢
