### ISSUE TITLE
Need ability to set isDisabled on each node individually

### ISSUE THREAD

**Issue by FrankHalbach** [riophae/vue-treeselect#71]
Hello,

Great library. I would like to use vue-treeselect in my project.
However, I need the ability to set the isDisabled property on each node individually.
When a branch node is disabled it shouldn't automatically disable all descendants in my scenario.

I think this would offer more flexiblity.

Any thoughts? 

Example:
World
-EU
--Fra
--Uk
-Na
-etc.

Some users may only have access to one (or multiple) region or one country.
if a user has access to Fra only he should not be able to select World, EU, Uk, etc. but only Fra.

Frank

**Comment by riophae** [comment]
Hi Frank! Can you try flat mode? In this mode, children nodes won’t be automatically disabled.

**Comment by FrankHalbach** [comment]
Hi Li,

... I should have read the complete docs first. Works as desired in flat mode!

Thanks for the quick help!

Frank

**Comment by lerit** [comment]
你好,看到上面的答案,但是我的需求是单选,当前flat模式,给出警告:必须要求多选.
虽然可以通过limit:1限制,但是觉得不是根本解决方案.能否flat不限制单选多选呢,谢谢

**Comment by DoveAz** [comment]
> @riophae 你好,看到上面的答案,但是我的需求是单选,当前flat模式,给出警告:必须要求多选.
> 虽然可以通过limit:1限制,但是觉得不是根本解决方案.能否flat不限制单选多选呢,谢谢

+1
