### ISSUE TITLE
noChildrenText noOptionsText no can use

### ISSUE THREAD

**Issue by laosandegudai** [riophae/vue-treeselect#77]
I want to replace the default text,but it doesnt work.

                            loadingText="记载中"
                            noChildrenText="到头了"
                            noOptionsText="到头了"

**Comment by riophae** [comment]
你好，我刚刚试了一下，没有发现这个问题啊？可以提供更多信息吗？

**Comment by laosandegudai** [comment]
github上的代码无法编译成功，可否加强版本号的说明，我使用的时你的demo里面的cdn版本，或者我的用法错误。

**Comment by riophae** [comment]
没明白你的意思，你是通过 GitHub clone 之后编译会报错是吗？
CDN 版本应该是可以正常用没有区别的，方便贴一下调用的代码吗？

**Comment by riophae** [comment]
试试改成这样呢：

```html
<treeselect 
  v-model="value" 
  :multiple="true" 
  :options="options" 
  :load-options="loadOptions" 
  placeholder="选择目录" 
  loading-text="记载中" 
  no-children-text="到头了" 
  no-options-text="到头了" 
  />
```

注意，某些情况下，模板里 prop name 必须用连字符格式才行，驼峰格式 Vue 不认。

![image](https://user-images.githubusercontent.com/1289884/39797408-90b8b04e-538e-11e8-998c-c6baddc5e3dc.png)

**Comment by laosandegudai** [comment]
都忘了这个东西了，搞定，作者最漂亮。

**Comment by riophae** [comment]
哈哈！建议用 ESLint，可以帮助发现这类错误

**Comment by laosandegudai** [comment]
坑爹的项目，前端是jquery的，正在接入vue。

**Comment by sgf** [comment]
@laosandegudai 大佬 你们Jquery 怎么获取这个控件的选中后的值啊
