### ISSUE TITLE
搜索类别Bug

### ISSUE THREAD

**Issue by markh5** [riophae/vue-treeselect#78]
https://vue-treeselect.js.org/#basic-features
文档中的例子，如果搜索Fruits的话，展开子项，子项却没有。

**Comment by riophae** [comment]
你好！谢谢反馈，这里确实需要调整

**Comment by markh5** [comment]
多谢，劳烦调整后告知下

**Comment by riophae** [comment]
你好，刚刚发布的 v0.0.27 修正了这个问题
