### ISSUE TITLE
How can i init the first value  when i load the data of async?

### ISSUE THREAD

**Issue by laosandegudai** [riophae/vue-treeselect#79]
我使用了ajax加载数据，当我初始化这个组件时，我的初始值绑定不在第一次加载的集合中，就会出现unknow的提示，如何绑定呢。

**Comment by riophae** [comment]
你好！可以参考下这个：https://github.com/riophae/vue-treeselect/issues/4

 有两种方式，一种是使用 valueFormat=object，需要你把 label 和 id 都保存起来，然后传给 vue-treeselect 的 value 也得把 label 和 id 一并传过去，这样就可以做到当选项还没有 AJAX 加载进来时，就能知道 label 的值。

还有一种是，初始时就用 loadOptions 把默认选项也一并加载进来。这需要修改后端的 API。

**Comment by riophae** [comment]
关于这个问题文档里面应该提到的，我一直没做，抱歉哈

**Comment by laosandegudai** [comment]
目前参考#4解决问题，谢谢作者了，作者最漂亮。
