### ISSUE TITLE
设置了默认选中的值，但是删除不了

### ISSUE THREAD

**Issue by tong822218** [riophae/vue-treeselect#81]
多选情况下，异步请求了数据后，设置默认选中的值，但是选中的值点击差号删除不掉，新增的值可以

**Comment by riophae** [comment]
你好！我刚刚试了下，没能重现。方便把完整调用代码贴上来吗？

**Comment by tong822218** [comment]
感谢大神回复，这个问题我解决了，在这里说一下，首先下面是我的代码
`                                           <treeselect 
                                                    v-model="orgModal" 
                                                    placeholder='请选择...' 
                                                    :multiple="true" 
                                                    :flat="true"
                                                    :load-root-options="loadRootOptions" 
                                                    :auto-load-root-options="true" 
                                                    style="margin-left:70px;"
                                                     />

data:{
orgModal: [],
},
methods:{
loadRootOptions (callback) {
            if (called) {
                setTimeout(() => callback(null, this.orgTreeDateForTree), 1000)
            } else {
                called = true
                setTimeout(() => callback(new Error('test')), 1000)
            }
        },
 // 表格内查看按钮中 设置组织机构
        setOrgSelf (item) {
            var a = item.orgIds.split('|'),
                i = 0,
                ac = []
            for (i = 0; i < a.length - 1; i++) {
                ac[i] = a[i]
            }
            this.orgModal = ac
            this.setorgid = item.userId
            this.setorglinkself = item._links.patch_set_user_org.href
            this.setOrgmodal = true
        },
}

`
大体意思就是我有个按钮，点击调用setOrgSelf获取当前选中的值赋值给orgmodal,然后页面效果都没有问题

![image](https://user-images.githubusercontent.com/9926531/39790531-46519e14-5369-11e8-9f87-ca73ab6f2d11.png)
但是点击右侧的删除按钮这条记录删除不了，后来我发现，setOrgSelf 方法中var a = item.orgIds.split('|'),
这句代码获取出来的值是字符串形式['1','2','3']   我把它里面的值改成数字形式就OK了[1,2,3]
我想这是不是也算是个bug,这个问题不容易发现，我也是花费了很长时间才蒙对了 😆

**Comment by tong822218** [comment]
刚才html代码没有发上  
<treeselect 
                                                    v-model="orgModal" 
                                                    placeholder='请选择...' 
                                                    :multiple="true" 
                                                    :flat="true"
                                                    :load-root-options="loadRootOptions" 
                                                    :auto-load-root-options="true" 
                                                    style="margin-left:70px;"
                                                     />

**Comment by tong822218** [comment]
`<treeselect 
      v-model="orgModal" 
       placeholder='请选择...' 
       :multiple="true" 
       :flat="true"
       :load-root-options="loadRootOptions" 
       :auto-load-root-options="true" 
       style="margin-left:70px;"/>`

**Comment by riophae** [comment]
对的！就是这个 `id` 类型的问题了。这个不是 bug 哈，类型必须严格区分的。
此外还有个建议，我在例子中用那个 `called` 变量是为了演示异常处理，但实际使用中肯定不是这个样子的，一般都是网络错误或者后端返回错误之类的情况，所以像你这个地方，应该把这个 `called` 变量去掉的。

**Comment by tong822218** [comment]
OK 多谢了

**Comment by riophae** [comment]
我之前就考虑过要不要把 id 为数字类型和字符串类型两种情况做一下严格区分（因为 JavaScript 在很多地方都有自动类型转换），但是当时觉得自己可能想多了。

今天看了你这个情况后发现还是有必要多做一些处理的。之后会做调整，如果注册的选项 id 是数字类型，而 value 里面是字符串类型，则应该显示这个节点不存在，而不是像你这里仍然能把 label 之类的都正常显示出来。这样改动后问题更容易暴露出来。

**Comment by tong822218** [comment]
对的，我刚才说算是bug就是这个意思，，，维护这样的开源项目也很辛苦啊，每天还得抽出时间来回复，哈哈

**Comment by riophae** [comment]
哈哈！谢谢理解~

**Comment by kennponn** [comment]
我也遇到了 哈哈
