### ISSUE TITLE
在bootstrap中样式乱了

### ISSUE THREAD

**Issue by wangzhiman** [riophae/vue-treeselect#83]
在bootstrap中下拉中的树样式乱了，请教一下怎么解决

**Comment by riophae** [comment]
你好，可以提供一下截图吗？

**Comment by wangzhiman** [comment]
![a](https://user-images.githubusercontent.com/12542854/39810706-94fb6956-53b8-11e8-9288-82482b720ffc.jpg)

**Comment by riophae** [comment]
感觉是调用得不对，看看控制台有报错吗？以及，方便把调用代码贴上来吗？

**Comment by wangzhiman** [comment]
![qq 20180509184605](https://user-images.githubusercontent.com/12542854/39810868-458c979a-53b9-11e8-92c0-a325c6d75d13.png)

**Comment by wangzhiman** [comment]
控制台没报错，您稍等，我贴代码

**Comment by wangzhiman** [comment]
![qq 20180509184953](https://user-images.githubusercontent.com/12542854/39810984-cba85fa8-53b9-11e8-8a47-7370a928ced4.png)

**Comment by wangzhiman** [comment]
`Vue.component('treeselect', VueTreeselect.Treeselect)
		
	    new Vue({
	      el: '#app',
	      data: {
	        // define default value
	        value: null,
	        // define options
	        options: [ {
	          id: 'a',
	          label: 'a',
	          children: [ {
	            id: 'aa',
	            label: 'aa',
	          }, {
	            id: 'ab',
	            label: 'ab',
	          } ],
	        }, {
	          id: 'b',
	          label: 'b',
	        }, {
	          id: 'c',
	          label: 'c',
	        } ],
	      },
	    })`

**Comment by wangzhiman** [comment]
![aaa](https://user-images.githubusercontent.com/12542854/39811176-6fbbfdfc-53ba-11e8-9c7b-0780ff9a42bc.png)

**Comment by wangzhiman** [comment]
主要就是这三块代码，是不是其他样式影响了

**Comment by riophae** [comment]
嗯，我刚刚试了一下，无论是搭配 Bootstrap 3 还是 4 都是可以正常工作的，所以应该跟 Bootstrap 没关系。

你先试着加一下这个参数：`alwaysOpen=true`，最终是类似下面这样：

```html
<div id="app">
  <treeselect :options="options" :multiple="true" :always-open="true" v-model="value" />
</div>
```

然后打开控制台，用审查元素功能选中 vue-treeselect 的复选框这一块，然后观察 HTML 结构是不是类似下面截图里这样：

![snipaste_2018-05-09_18-59-50](https://user-images.githubusercontent.com/1289884/39811499-7526053e-53bb-11e8-8cfb-3b918e96a90e.png)

**Comment by wangzhiman** [comment]
![sddfss](https://user-images.githubusercontent.com/12542854/39811719-5f951646-53bc-11e8-8ae1-96c8dffe0468.png)

**Comment by riophae** [comment]
果然，现在问题就在这了，我上面截图里是有 `<label class="vue-treeselect__label">` 这个东西的，而你这里没有，很奇怪

**Comment by riophae** [comment]
我印象中之前其他人反映过类似问题，正在找

**Comment by riophae** [comment]
对了，请问你的 Vue 版本是多少？可能跟这个有关系

**Comment by wangzhiman** [comment]
找到问题了，好像是vue的版本问题，我换成cdn引入，就正常了

**Comment by wangzhiman** [comment]
谢了
