### ISSUE TITLE
CSS transition for opening/closing branches

### ISSUE THREAD

**Issue by wickkidd** [riophae/vue-treeselect#86]
Thanks for solving https://github.com/riophae/vue-treeselect/issues/85 so quickly. On a related note, it would be nice if we could also have transitions for opening/closing branches (.vue-treeselect__list).

For example, if the children of a branch have the same labels as the siblings which follow that branch, opening that branch makes it look like the siblings have simply moved to the right a few pixels.

https://github.com/riophae/vue-treeselect/blob/42155af71d12373dd3be4edccb04131501cd98a1/src/components/Option.vue#L31

**Comment by riophae** [comment]
Hi Brian! I'd like to ask for your opinion. Which way do you prefer to customize the style? For example, is it okay for you to compiling LESS yourself, or you think that's too complex and just wanna override the compiled CSS? Or even other approaches...

**Comment by riophae** [comment]
Like [react-select](https://github.com/JedWatson/react-select/blob/master/less/select.less), currently vue-treeselect already has a lots of LESS variables that you can redefine values.

**Comment by wickkidd** [comment]
The issue with redefining less variables is that it requires the user to compile less (and have a less-loader if using webpack). It also doesn't solve the problem of renamed selectors. In my case we use SCSS so I’d still end up overriding the generated css anyway. Having both less and scss as options would be cool. In fact, you could even use something like https://github.com/ekryski/less2sass to provide both. 

Another thing you could do is provide props to the vue-treeselect component for adding css selectors to certain elements (menu-selector-name=".my-class-name"). As long as the amount of them didn’t grow too large it would be manageable. If you make sure to use the minimum amount of specificity (just its class) then as long as the user imports your less/css first, it will take any styles they write over the ones you write. This would allow you to change selector names without breaking their styles.

**Comment by wickkidd** [comment]
Works well. Thanks again.
