### ISSUE TITLE
vue-treeselect ， v-model 相关的问题

### ISSUE THREAD

**Issue by zgj233** [riophae/vue-treeselect#9]

**Comment by zgj233** [comment]
当一个节点下面的所有子节点都被选中时，`v-model` 等于这个父节点的id，怎么取消这一特性？让`v-model`还是保留选取的所有子节点id，而不是保留一个单独的父节点id

**Comment by riophae** [comment]
可以用 :flat="true"

Regards,
Riophae Lee
________________________________

**Comment by zgj233** [comment]
好酷

**Comment by zgj233** [comment]
@riophae  朋友你遇见过这种情况没有， 就是一旦我设置了`:flat="true"`, 那么我默认已经选择了的项，不能点击x 取消失效， 只有点击 `input` 最右侧的x, 才能把默认已选择项清空。
但是新加入的项又是正常的。
我没有设置`:flat="true"` 时, 一切正常

**Comment by riophae** [comment]
嗯，能否用这个 https://codepen.io/riophae/pen/MExgzP 写一个重现 bug 的 demo？

**Comment by j1wu** [comment]
非常棒的项目👍
正巧碰到个类似的需求，想请问下不知是否支持：只添加子节点的id，选中父节点即添加所有其子节点id，但不添加父节点id。

**Comment by riophae** [comment]
@j1wu 之前有考虑过，但是没有实现。我可以尝试一下。谢谢你的反馈！
不过有个问题需要进一步明确一下，点击父节点的时候，若只添加子节点 id，若某个子节点还有子节点，这种情况你觉得怎么处理比较好？

**Comment by j1wu** [comment]
@riophae 谢谢回复！确实，我那个需求太过具体了，在我当前的应用场景里没有子节点下面还有子节点的情况，不用为这个需求耽误时间了哈，再次感谢🙏

**Comment by riophae** [comment]
@j1wu 不是的，就是……我要实现这个话，必须得考虑这种情况……所以就征求一下大家的意见……之前之所以没做，也是因为这些细节的地方不知道怎么处理比较好

**Comment by mythbobo** [comment]
强烈要求只选择叶子节点功能,因为很多情况都是返回的是叶子节点的ID组,这样后端拿到数据才可用

**Comment by mythbobo** [comment]
类似于elementUI的tree组件,他可以返回前被选中的节点所组成的数组，也可以返回所有叶子节点组成的数组。。望增加此功能。。感谢啊。

**Comment by riophae** [comment]
@J1wu @mythbobo 抱歉拖了这么久，只选择叶子节点的功能在 v0.0.15 中终于实现了，请参考文档：https://vue-treeselect.js.org/#prevent-value-combining

**Comment by tong822218** [comment]
朋友你遇见过这种情况没有， 就是一旦我设置了:flat="true", 那么我默认已经选择了的项，不能点击x 取消失效， 只有点击 input 最右侧的x, 才能把默认已选择项清空。
但是新加入的项又是正常的。
我没有设置:flat="true" 时, 一切正常

你好朋友 这个问题解决了吗 我也遇到了

**Comment by gyg0522** [comment]
想拿到 选中的数据 ；
