### ISSUE TITLE
怎么样获取当前选中的节点的ID

### ISSUE THREAD

**Issue by wangzhiman** [riophae/vue-treeselect#90]
请教一下怎样获取当前选中的节点的ID

**Comment by riophae** [comment]
如果你用了 `v-model` 的话，比如：

```html
<treeselect v-model="value" :multiple="true" :options="options" />
```

那么这个 `value` 里面就是当前选中的节点的 id。如果是多选模式，它会是 id 数组。

**Comment by wangzhiman** [comment]
那我在js中怎样获取这个值？还有就是表单提交的话，怎样提交到后台

**Comment by riophae** [comment]
如果是用传统表单（非 AJAX）提交的话，你可以添加一个 `name` 参数，也就是你要提交的字段名称，比如：

```html
<treeselect v-model="value" :multiple="true" :options="options" name="value" />
```

然后 vue-treeselect 会渲染相应的 hidden field 出来。

如果是 AJAX 提交的话，建议先看看 Vue 官方教程吧……

**Comment by wangzhiman** [comment]
好的，多谢了，js获取的方法也会了
