### ISSUE TITLE
查询数据返回为空（bug）

### ISSUE THREAD

**Issue by ayiaq1** [riophae/vue-treeselect#91]
bug地址：https://codepen.io/ayiaq1/pen/yjjeWN

查询的时候单独请求接口然后修改 options，数据已经修改了，但是下拉菜单为空
<treeselect @search-change="selectSearchChangeFun"
    v-model="value"
    searchNested
    :options="metaDatas"/>

this.metaDatas=[{label:'123'}]

查询接口里面单独修改数据：
selectSearchChangeFun(query){
   this.metaDatas=[{label:'456'}]
}

![1](https://user-images.githubusercontent.com/3860498/39919745-35fb3b9e-5547-11e8-8ed8-2c3477677728.jpg)

**Comment by riophae** [comment]
你好，这个不是 bug 哈，是因为现在 vue-treeselect 还不支持异步搜索，目前在开发中

**Comment by riophae** [comment]
你好！v0.0.31 刚刚发布了，现在支持异步搜索了：https://vue-treeselect.js.org/#async-searching
