### ISSUE TITLE
Question: passing/retrieve additional elements other than" id" and "label"   

### ISSUE THREAD

**Issue by topegret** [riophae/vue-treeselect#95]
say the sever passing me an array of objs like this.
 [  {"id":"1","label":"car", "price":"xyz", "desc":"sth sth sth"},
     {"id":"2","label":"bike", "price":"aa", "desc":"blah blah blah"}
]

How can I display respective price and desc info while the user selected the label from the drop down.  thanks!

**Comment by ittus** [comment]
You can use `node.raw` in scope https://stackoverflow.com/a/50461474/2303610

**Comment by topegret** [comment]
Yes,`<p v-if="value">Price: {{ value.price }} Description: {{ value.desc }}</p>` is what I want if it works.  But I am not sure I am able to get the value as an object .i.e. not be able to display {{value.price}} nor {{value.desc}}.  Does the code above   `:value-format="object"` do the trick?   sorry. I am new to Vuejs. I tested your code and can not make it work. @riophae . thanks!

**Comment by ittus** [comment]
@topegret @riophae 

I think it's `value-format="object"` instead of `:value-format="object"`
```vue
<template>
  <div>
    <treeselect v-model="value" :options="options" value-format="object" />
    <p v-if="value">Price: {{ value.price }} Description: {{ value.desc }}</p>
  </div>
</template>
```

**Comment by riophae** [comment]
@topegret @ittus Sorry! You are right, it should be without the `:`.

**Comment by topegret** [comment]
seems this snippet won't work.the browser will 'hiccup' on '{{value.price}}' and '{{value.desc}}'. I am thinking to add a method to parse the object and then display it. 

 `<template>
  <div>
    <treeselect v-model="value" :options="options" value-format="object" />
    <p v-if="value">Price: {{ value.price }} Description: {{ value.desc }}</p>
  </div>
</template>`

**Comment by riophae** [comment]
@topegret Hey! Can you give more information on your problem? Then I can better help you.

**Comment by topegret** [comment]
thanks @riophae and @ittus . it works now. 
 In this example, from outside of the treeselect tag.  using `{{value.map(item=item.price}}`  and `{{value.map(item=item.desc}}` will get only 'price'  and 'desc' displayed. That is what i want.

**Comment by riophae** [comment]
Yeah, you are using the multi-select mode. The example previously given is single-select mode.
